### ISSUE TITLE
Distribute cookies?

### ISSUE THREAD

**Issue by joehillen** [bitly/oauth2_proxy#101]
We are currently running this on 4 different hosts, all under the same domain via round robin DNS.

Something we run into is that a user might have to login multiple times if they end up on a different hosts between sessions. It would be nice if there were a way to distribute cookies between all the proxy hosts. I'm curious how you think that could be built.

Another issue is that cookies don't seem to persist on disk at all, so everyone has to re-login if there is a host restart. Maybe a distributed datastore could be leveraged to solve both issues. Maybe [etcd](https://github.com/coreos/etcd)?

Thoughts? Ideas?

**Comment by jehiah** [comment]
@joehillen The server side is stateless so there is no need to store cookies there. You shouldn't be having any issues w/ different instances treating things differently (we use it across several subdomains w/o a problem at Bitly). Do your instances all have the same configuration? Is it possible they have different cookie secrets?

**Comment by jehiah** [comment]
Also, what version code are you running and is there anything in the logs on the request that triggers authentication that gives an indication of what the issue might be?

**Comment by joehillen** [comment]
Oh ok. I'll investigate this sometime then, I just assumed it was a distribution issue. Probably secrets or a short cookie lifetime. 

@jehiah Thanks for the quick response.

**Comment by jehiah** [comment]
If you explicitly want authentication to last for longer than the cookie TTL you can also look at the feature added recently in #88
