### ISSUE TITLE
authenticated-emails-file not properly checked with google apps domain

### ISSUE THREAD

**Issue by groob** [bitly/oauth2_proxy#103]
Hi,

I'm running the latest version of oauth2_proxy with an email file and google-apps-domain. I have only 1 user in my emails file, who is not me. However, I'm still able to authenticate to the service as myself even though I'm not on the list of allowed emails. 

```
./oauth2_proxy \
	-cookie-secret="secret" \
	-client-id="foo" \
	-client-secret="secret" \
	-upstream=http://127.0.0.1:3000/ \
	-authenticated-emails-file=/etc/emails \
	-google-apps-domain="domain.org"
```
Right now any user with an @domain.org can authenticate regardless of the file.

**Comment by groob** [comment]
I might be reading the code wrong, but from the looks of it, the validator function only checks that the domain for each user in `authenticated-emails-file` matches the google apps domain. Is this intended? 

I'm looking to restrict access to a particular group/suborg.

**Comment by jehiah** [comment]
@groob I think you are running into just poor documentation here.  The `--google-apps-domain` option is intended to whitelist a whole email domain. I've been considering renaming it to something like `--whitelist-email-domain` to make that clearer (not to mention `oauth2_proxy` applies that value for any provider not just google)

If you want to just validate w/ a list of emails you should be fine just skipping the domain in `google-apps-domain`.

**Comment by groob** [comment]
Thank you for clearing that up!

I actually added the -google-apps-domain flag because I kept getting 'Invalid Account'. Did not realize that the -authenticated-emails-file was necessary.

**Comment by jehiah** [comment]
you should be able to use either. Were you getting an error using just `--authenticated-emails-file` ?
