### ISSUE TITLE
validator.go:24: undefined: WatchForUpdates

### ISSUE THREAD

**Issue by dbiswas1** [bitly/oauth2_proxy#105]
Hi i am new using Go, i want to setup enable oauth in Nginx when i follow instruction i get following error
go get github.com/bitly/oauth2_proxy
# github.com/bitly/oauth2_proxy
../bitly/oauth2_proxy/validator.go:24: undefined: WatchForUpdates

Please help me

**Comment by mbland** [comment]
Sorry, that was my fault. Either you're running Plan 9 or Solaris, or using a version of Go before 1.3. You can check your version of Go by running `go version`. Whatever the case, #106 should fix it. You can try to pull the branch for #106 and see if it fixes the problem by running:

```shell
$ cd $GOPATH/src/github.com/bitly/oauth2_proxy
$ git remote add 18f https://github.com/18F/oauth2_proxy
$ git fetch 18f fix-watcher-build-tags
$ git checkout fix-watcher-build-tags
$ ./test.sh
$ go build
```

**Comment by mbland** [comment]
OK @dbiswas1, you should be able now to run `go get github.com/bitly/oauth2_proxy` without problem. Let me know if it still doesn't work for you.

**Comment by dbiswas1** [comment]
Thanks a lot it fixed
