### ISSUE TITLE
Error 500: https://accounts.google.com/o/oauth2/token: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by jos3k4** [bitly/oauth2_proxy#112]
I've created the configuration file with all the necessary properties and my stuff (Configured with Google) , I've executed the service and it works properly. It ask me for the Google Account I introduce it (I have 2 step auth enabled) and when the Consent screen appear and I click in Accept. the following error appear.

```
2015/05/31 08:25:08 ErrorPage 500 Internal Error Post https://accounts.google.com/o/oauth2/token: x509: certificate has expired or is not yet valid

```

Maybe something is missing or is wrong in my configuration file. I need some help at this point.

**Comment by jos3k4** [comment]
Maybe is useful for others... but I've found that the application should run as HTTPS https://developers.google.com/identity/protocols/OAuth2UserAgent

**Comment by jehiah** [comment]
@jos3k4 can you check the system date on the machine where you are running? 

The part of the log where it says "or is not yet valid"  implies that your system date is behind. If the log entry you posted is recent, it has a date of May 31st but it's now June 12th.

**Comment by jos3k4** [comment]
@jehiah Thanks for the fast answer... I'm testing it in a test machine and it doesn't have the correct time configuration, thanks! 

But now , I obtain a different error.

```
500 Internal Error

api request returned non 200 status code

```

**Comment by jos3k4** [comment]
Thanks! I solved it updating the time on the machine (I'm using a test box)

**Comment by jos3k4** [comment]
I know that probably this is not the thread for ask it, but for avoid open another issue/question... How can I redirect to another context? I mean, the redirect_url should point to the server that have the Google Auth API context (/oauth2/callback) but if I want to redirect to another one, can I do it?

**Comment by jehiah** [comment]
@jos3k4 can you clarify what you mean by "redirect to another context"? I'm not sure i follow so perhaps if you share what you are trying to accomplish with your setup i can give some guidance.

The `upstream` option specifies where traffic goes after it passes through oauth2_proxy (assuming it's an authenticated session). If you specify multiple upstream addresses, with different path prefixes `oauth2_proxy` should just "do the right thing". (ie: you can send `/a/` to one upstream and `/b/` to another)

**Comment by mbland** [comment]
@jos3k4 If by "redirect to another context" you mean use the host running oauth2_proxy to handle authentication for another host, such as when you're using a single-sign on (SSO) across multiple hosts, there is a way to configure that. See the [SSO.md from my project](https://github.com/18F/hub/blob/master/deploy/SSO.md), which was inspired by #12.

**Comment by jos3k4** [comment]
@jehiah Well, my idea is use this API for check the users credentials and then do something like a ProxyPass to the application that the user wan't to see. My target is replace AuthBasic of Apache using this nice service. It can be possible?

**Comment by jehiah** [comment]
@jos3k4 correct `oauth2_proxy` **is** a `proxy_pass` which authenticates requests. `upstream` is the address of where requests are proxied to, and only authenticated requests are proxied along.

**Comment by jos3k4** [comment]
Thanks for the help guys, I like this project.
