### ISSUE TITLE
Use S3 as a backend

### ISSUE THREAD

**Issue by willejs** [bitly/oauth2_proxy#121]
It would be great if i could put this in front of my private S3 buckets, and use google auth proxy to authenticate to them.
Could you add the concept of a backend, and have an option to use s3?

**Comment by jehiah** [comment]
@willejs I have something in mind =)

**Comment by jehiah** [comment]
@willejs It's a little rough around the edges, but does [jehiah/private_s3_httpd](https://github.com/jehiah/private_s3_httpd) work for you?

**Comment by sricola** [comment]
or go `oauth_proxy` -> `nginx` - > `s3` (as an nginx upstream)

**Comment by ploxiln** [comment]
Plain nginx upstream won't work for a *private* s3 bucket, which is the request here. I did think that for a second, but realized that there's not much cause to use oauth2_proxy (just) for a public s3 bucket.

**Comment by mreiferson** [comment]
well let's just have a code review reunion in here...

paging @jlintz @jphines @mccutchen @dlotterman

**Comment by sricola** [comment]
@ploxiln yes it would, you can use a s3 auth token. to request the file from the upstream and then serve it via `nginx`

**Comment by jehiah** [comment]
@sricola oh? point me to some docs for that as that would sort of obsolete the code i just wrote =)

**Comment by jlintz** [comment]
did someone call a top 2% python coder?

*steps in*

Yea @sricola is correct, you can actually proxy to s3 and set your tokens in the headers , here's a good example https://coderwall.com/p/rlguog/nginx-as-proxy-for-amazon-s3-public-private-files , assuming I understood things correctly

**Comment by jehiah** [comment]
nice, that's good to know.

**Comment by ploxiln** [comment]
It looks like every access to S3 still requires a signature. That blog post suggests including the signature (and expires timestamp) as a parameter in all the public URLs (and then adding other needed headers/parameters in nginx).

**Comment by sricola** [comment]
You can modify the request before passing it though the upstream within
Nginx - thereby adding the signature et al without having the original
request need it.

On Tuesday, July 7, 2015, Pierce Lopez <notifications@github.com> wrote:

> It looks like every access to S3 still requires a signature. That blog
> post suggests including the signature (and expires timestamp) as a
> parameter in all the public URLs (and then adding other needed
> headers/parameters in nginx).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitly/oauth2_proxy/issues/121#issuecomment-119392829>.
>


-- 
--
srivatsa // hi@sri.so

**Comment by ploxiln** [comment]
... but then nginx needs to know or calculate the signature needed for each file (it'll be different). So you'd need a location clause for each file, or an nginx plugin which can do that...

**Comment by mreiferson** [comment]
:joy:

**Comment by sricola** [comment]
Well. The signature is actually pretty trivial if you have the access
key/secret. Or you can use IAM roles and fetch credentials in realtime from
the instance meta data.

On Tuesday, July 7, 2015, Matt Reiferson <notifications@github.com> wrote:

> [image: :joy:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitly/oauth2_proxy/issues/121#issuecomment-119408151>.
>


-- 
--
srivatsa // hi@sri.so

**Comment by sricola** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html

On Tuesday, July 7, 2015, Srivatsa Ray <hi@sri.so> wrote:

> Well. The signature is actually pretty trivial if you have the access
> key/secret. Or you can use IAM roles and fetch credentials in realtime from
> the instance meta data.
>
> On Tuesday, July 7, 2015, Matt Reiferson <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> [image: :joy:]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bitly/oauth2_proxy/issues/121#issuecomment-119408151>
>> .
>>
>
>
> --
> --
> srivatsa // hi@sri.so
>


-- 
--
srivatsa // hi@sri.so

**Comment by ploxiln** [comment]
ok yes it's not particularly hard, if you've installed the *out-of-tree* [ngx_set_misc module](http://wiki.nginx.org/HttpSetMiscModule) to get `set_hmac_sha1` and `set_encode_base64`, and composed the string to sign correctly.

jlintz' "good example" link does not do these things. so I guess my point is that it's probably an equivalent amount of effort and config/deploy management to use something like private_s3_httpd

**Comment by sricola** [comment]
LOL. I'd rather recompile a widely used open source package - with some extra options than write custom code to re-invent the wheel. Thats just me, and you don't have to agree with that viewpoint.

**Comment by jehiah** [comment]
It's ok @sricola [private_s3_httpd](https://github.com/jehiah/private_s3_httpd) now counts as a widely used open source package, so you can use that. No extra options or recompile needed.

**Comment by mccutchen** [comment]
I want to frame this thread and hang it on my wall.

:100: :100: :100:

**Comment by willejs** [comment]
@jehiah That code looks like it would work, for me, but...
It would be nicer if oauth2_proxy would support it as a backend too? is it out of scope for the project?

**Comment by jehiah** [comment]
@willejs Yeah, I've been pondering that. I think i'm landing on the side of "out of scope" in preference of keeping this focused on authentication not file serving.
