### ISSUE TITLE
Question about upstreams

### ISSUE THREAD

**Issue by jos3k4** [bitly/oauth2_proxy#124]
Hello, Sorry for the simple question, but I didn't found something related with this.

I know that you can define some upstreams with different context (/App1, /App2) in order to create some routing logic, but I have some problems with this configuration.

When I use the following configuration in the upstreams.
```
 upstreams = [
     "http://server1/App1",
     "http://server2/App2" ]
```

Routing is working but the context "/Appx" is also sent to the server, can I avoid this? I mean... using the configuration that I posted but when an user call oauth2_proxy with App1 context, the "ProxyPass" request go for http://server1/ instead of http://server1/App1.

Thanks for the help, I like this project too much!

**Comment by jehiah** [comment]
@jos3k4 you are correct, `oauth2_proxy` will not rewrite requests (or responses) like you are describing. 

The primary options you have are to a) use subdomains so you have `app1.domain.com` and `app2.domain.com` and set your cookie_domain to `.domain.com` so they can share authentication, or b) set your upstream as an intermediate `nginx` endpoint and configure request/response url rewriting there.

**Comment by jos3k4** [comment]
@jehiah thanks for the answer.
With the option a) you mean have something like this?

```
 upstreams = [
     "http://app1.company.com",
     "http://app2.company.com" ]
```

If you mean that I've already tried ir and the application returns the following trace.
```
panic: http: multiple registrations for /

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0xc20800b020, 0x7c4810, 0x1, 0x7fd79a471568, 0xc20801ee60)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1557 +0x244
main.NewOauthProxy(0xc20800cd80, 0xc20801eca0, 0x1)
	/Users/jehiah/projects/tmp_build/src/github.com/bitly/oauth2_proxy/oauthproxy.go:98 +0x3d3
main.main()
	/Users/jehiah/projects/tmp_build/src/github.com/bitly/oauth2_proxy/main.go:92 +0x14c7

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.go:90
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:712
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

```

I understand is normal behaviour the application doesn't allow two routing paths pointing to "/"

Probably for now I will use multiple instances of oauth2_proxy for each application on my internal network. Again thanks for all.

**Comment by mbland** [comment]
For a one-cookie-multiple-domain example, check out [the 18F/hub SSO configuration](https://github.com/18F/hub/blob/master/deploy/SSO.md), inspired by #12. It is a little subtle, but very effective. The one thing the `README` doesn't get into is the individual `location` definitions; you can see those in [the 18F/hub nging vhost configs](https://github.com/18F/hub/tree/master/deploy/etc/nginx/vhosts).

**Comment by jos3k4** [comment]
The implementation that I've done is fine for now, thanks for the help to everyone!
