### ISSUE TITLE
Issues with oauth_proxy behind two proxies

### ISSUE THREAD

**Issue by elssar** [bitly/oauth2_proxy#135]
I had a setup where I had Kibana running behind oauth2_proxy v 1.1.1, which was running behind nginx, which terminated SSL. It all worked without a hitch.

[ nginx (ssl termination)] --> [ oauth2_proxy 1.1.1 ] ---> [ kibana ]

Now I'm trying to setup oauth2_proxy v2.0.1 for Kibana in a AWS EBS environment. This time around, the AWS ELB handles SSL termination and proxies to nginx on the instance, which in turn proxies to oauth2_proxy

[ ELB (ssl termination) ] --> [ nginx ] --> [ oauth2_proxy 2.0.1 ] --> [ Kibana ]

This does not work. I can authenticate just fine, but after that oauth2_proxy keeps giving me 404s. I have manually checked that Kibana is running.

I have checked out #62 but it doesn't really help me.

Does anyone know whats going on?

A sample log written by oauth2_proxy

```terminal

{{IP}} - {{email}} [18/Aug/2015:05:57:26 +0000] {{host}} GET - "/" HTTP/1.0 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/37.0.2062.120 Chrome/37.0.2062.120 Safari/537.36" 404 19 0.000
```

And the command I use to start oauth2_proxy in my upstart file

```terminal
exec ./oauth2_proxy     --email-domain="{{domain}}"     --upstream=http://{{IP}}:5601     --cookie-secret={{secret}}     --cookie-secure=true     --client-id={{client_id}}     --client-secret={[client_secret]}     --redirect-url="https://{{domain}}/oauth2/callback"     --http-address="127.0.0.1:4180" >> /var/log/oauth2_proxy.log
```

**Comment by elssar** [comment]
I played around a bit, and it works if I don't use SSL. So I'm guessing that oauth2_proxy expects the proxy in front of it to terminate SSL. If that is the case, then can I make this work by having nginx forward some headers?

**Comment by elssar** [comment]
Figured it out. Tiny little thing. Nginx was setting the `X-Scheme` to `http`, just need to set it to `https` and everything works.

**Comment by jehiah** [comment]
glad to hear you were able to work this one out :smile:
