### ISSUE TITLE
Different authorized email list per upstream

### ISSUE THREAD

**Issue by jideshv** [bitly/oauth2_proxy#138]
Hi, this is related to #12 and #125.  I have the following scenario and trying to decide whether I fork the oauth2_proxy code and add this feature or if there is a builtin way of already doing this:

upstream1: http://partnerserver:1000/partner1  (authorized email list of partner1)
upstream2: http://partnerserver:1000/partner2  (authorized email list of partner2)

What we are trying to do is have a simple way of providing access to external parties and manage all the access control in one place.  I know we could pass the http basic auth headers but then we manage access control in two places.

Thoughts on the right way to do this without setting up multiple oath2_proxy instances?

**Comment by jehiah** [comment]
There isn't a way to have separate authorization settings on the same oauth2_proxy. You will need multiple instances.

You should be able to setup nginx (or any similar reverse proxy) in front of two oauth2_proxies that share the same settings (so they can each read the same session cookie) and then configure each oauth2_proxy w/ an appropriate authorized list and upstream. Set nginx to poing `/` at one oauth2_proxy, and `/partner2` at the second.

You could also accomplish the same thing with different subdomains so you have `partner1.company.com` and `partner2.company.com` each backed by their own oauth2_proxy and allow both oauth2_proxies to share a session on domain `.company.com`.

**Comment by jideshv** [comment]
Thanks for the feedback.  This isn't an urgent need for us but having to setup multiple oauth2_proxies makes on-boarding/off-boarding a little more work.  Thanks again for the quick response.

**Comment by jehiah** [comment]
@jideshv out of curiosity, what provider are you using?

**Comment by jideshv** [comment]
@jehiah in the process of setting things up.  Planning on using the github provider which gives us the flexibility of giving our whole team access to our documentation server.  In the future we will ask some of our partners to view online documentation and I was looking for a simple way of allowing that without exposing the rest of the documentation space to them.

I like the simplicity of oauth2_proxy lets us add authentication to systems that don't have their own.  Also I suspect we will have the same challenges you wrote about in your blog after we get elasticsearch and graphite setup...  So many great tools out there but the perpetual overhead seems to be centralizing authentication to keep things simple for users.  I like how you solved that...
