### ISSUE TITLE
Google Offline Access Requested

### ISSUE THREAD

**Issue by ProTip** [bitly/oauth2_proxy#140]
Hello,

Every time I clear my cookies or visit the ```sign_in``` page(clears the cookies) I get a notice from Google that the app is requesting offline access next time I try to log in.  I don't see this with any of the other services I sign into with Google apps, is there a way to set it up so this does not happen?

**Comment by jehiah** [comment]
Some services perpetually accept email or authentication data (oauth2_proxy used to do this too!), but there are two things that drove this change that required offline access:

 1. oauth2_proxy gained the ability to pass an access token for the authenticated session to it's upstream. This means offline access with transparent renewing of the access token via refresh tokens.
 2. There are typically competing desires between long lived sessions (not forcing users to re-auth every hour, etc) and short sessions (ensuring that revoking permissions takes effect as quickly as possible). By using offline access, credentials are able to be revalidated frequently separate from the session life to quickly detect and revoke authorization changes (think for example, a google apps domain and you remove an email address/account, if there was an existing session to oauth2_proxy w/ that email address, you want to end it as quickly as possible and not wait for a week long session timeout).

#131 will change this behavior slightly by eliminating most cases where you see a re-login page.

Does that answer your question?
