### ISSUE TITLE
Static file serving

### ISSUE THREAD

**Issue by Tenzer** [bitly/oauth2_proxy#141]
It would be neat if oauth2_proxy could use a directory path as the backend instead of a HTTP server, ie. for generating documentation to static files which only should be accessible for people who have the right credentials.

It's not an urgent feature for me, but I am thinking it's something that may not involve a lot of work.

**Comment by jehiah** [comment]
@Tenzer interesting. I'd accept a patch that supported `file:///...` as a valid upstream setting. Want to take a pass at that?

(I wrote [`private_s3_httpd`](https://github.com/jehiah/private_s3_httpd) with a similar motivation with the only detail that serving files locally didn't fit my need)

**Comment by Tenzer** [comment]
Sure, I'd like to give it a stab although my experience with Go is somewhat limited. From what I can see by giving the project a quick glance, I need to add some logic in `NewOauthProxy()` in oauthproxy.go to add a `net/http.FileServer` as a handler on the `serverMux` being created. Does that sound correct to you?

**Comment by jehiah** [comment]
@Tenzer exactly. `http.FileServer` would be in place of `UpstreamProxy`  if the upstream protocol is `file:///`

**Comment by Tenzer** [comment]
Cool, I'll give it a shot later today and hopefully come up with a pull request :)

**Comment by jehiah** [comment]
feature added in #142
