### ISSUE TITLE
Protecting Multiple Domains

### ISSUE THREAD

**Issue by aimless55** [bitly/oauth2_proxy#143]
I'm currently using oath2_proxy to protect a single domain. Oauth2_proxy is listening on localhost:4180, which is served by nginx on foo.example.com. After a successful authentication, oauth2_proxy serves the application on localhost:9090.

This works great, but I now want to use oauth2_proxy to protect a second application (running on localhost:9000) on a second domain (bar.example.com).

I could run 2 different instances of oauth2_proxy, specifying a different config file for each, but since everything other than the upstream application is the same (same oauth app, same email domain, etc), I'm wondering if there is some way to accomplish this with a single oauth2_proxy instance.

Can this be done?

What I want is basically this:

    foo.example.com > oauth2_proxy > localhost:9090
    bar.example.com > oauth2_proxy > localhost:9000

**Comment by Tenzer** [comment]
It all depends on the paths used on the upstream services. Earlier this week I added some documentation to the [README file](https://github.com/bitly/oauth2_proxy#upstreams-configuration) on how to configure multiple upstreams in oauth2_proxy, that will hopefully be able to help you out, but the gist of it is that oauth2_proxy does routing based on the paths provided on the upstream servers. This however means that it cannot support multiple upstreams which ie. both supply `/` as the path.

@jehiah Would it make sense to support fragments in HTTP(S) upstreams as well, like it was done with the file:// URLs? That could potentially make setups using multiple upstreams easier to set up.

**Comment by mbland** [comment]
@aimless55 Another option, if you're comfortable with subtle nginx config hacking: https://github.com/18F/hub/blob/master/deploy/SSO.md

Those instructions were inspired by @skippy's example in #12. In practice, it's worked remarkably well.

**Comment by aimless55** [comment]
@mbland Perfect! Thanks.
