### ISSUE TITLE
Securing authentication across the public internet

### ISSUE THREAD

**Issue by mbland** [bitly/oauth2_proxy#146]
Short version: Should we add HMAC signatures when passing authenticated requests upstream?

I've been running [oauth2_proxy to implement single sign-on](https://github.com/18F/hub/blob/master/deploy/SSO.md) across different apps on different domains for some time, with great results. However, all of those different apps and domains are actually running on the same host.

Recently my team tried to use the same mechanism for an app running on a different host, across the public internet, and hit the thorny problem of being able to access the app both through the oauth2_proxy and when bypassing it completely. It just hit me that adding optional HMAC signatures to authenticated requests might do the trick. It would be up to the upstream application to check the signatures, but that's easy to implement.

Thoughts? (I'm already poking around the code.)

**Comment by jehiah** [comment]
Generally ++ on this. This need doesn't come up often but it would be useful. 

I'd love to hear your thoughts on details of what signing mechanism would work. Also, i could be interesting/useful in some cases if there was a separate open source project with a binary that received said secure requests and did the validation passing on only validated requests.

(A long time ago, #1 sort started to tackle this problem, but the specific need driving that work eventually disappeared)

**Comment by mbland** [comment]
Cool! So what I'm thinking is pretty straightforward: Once the proxy has authenticated a request, it'll do a SHA1 HMAC of the raw request body and add the result as a header, a la [GitHub webhooks](https://developer.github.com/v3/repos/hooks/#example). Then it's up to the client to store the shared key and check the signature of incoming requests. There could be a "default" secret key, and a mechanism to configure per-host/upstream secret keys if desired.

FWIW, I got the idea this weekend after implementing the [`github-webhook-validator` npm](https://www.npmjs.com/package/github-webhook-validator) that I'm using to add authentication to 18F Pages webhooks in 18F/pages-server#5.

Regarding the proxy to multiplex secured requests, heh, yeah, I thought about that, too... In our case, it wouldn't help, because our app infrastructure doesn't allow for restriction of incoming requests from a trusted IP, at least no _obvious_ way. But it might be a useful tool when you can deploy to a private subnet, I agree.

I'll get cracking!

**Comment by jehiah** [comment]
In the webhook case it's the body of the message you care about authenticating. Here, it could be the body on a `POST`, but it's more the authorization state, so the host, URL and headers (ie: cookies, passed access token, auth'd email address). That leads me to think we need an explicit list of things that are part of the HMAC.

**Comment by mbland** [comment]
@jehiah You beat me to the punch... :-)

So I just realized that GET requests won't typically have a request body. Inspired by http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html, I'm proposing the signature be a hash of something like: HTTP-Verb + "\n" + Date + "\n" + URI + GAP-Auth header.

How's that sound?

**Comment by mbland** [comment]
Actually this is what I'm now using, after some thought and experimentation, with each value separated by a newline:

* HTTP method
* Content-Md5
* Content-Type
* Date
* Gap-Auth
* URI
* Body

Any values not in the original request are represented by the empty string. Sound OK?

**Comment by mbland** [comment]
Oh right... Cookies and the passed-through auth token... Not sure how critical the host is, though, but perhaps that's my ignorance showing.

**Comment by mbland** [comment]
So here's the new package with the signature logic in my 18F/oauth2_proxy#hmac-signatures branch: https://github.com/bitly/oauth2_proxy/compare/master...18F:hmac-signatures?expand=1

How does that look so far? It's actually pretty straightforward stuff; it's easy to update the header set if we decide that what's there isn't what we actually want.

I'm now working on setting up the configuration and hooking it into the proxy. With the code in a dedicated package like this, I'm hoping that will make it easy for go programs to just import and use it, and I may add a basic "proxy proxy", too, dedicated to passing through signed requests, as you'd mentioned earlier, @jehiah.
