### ISSUE TITLE
An /auth endpoint to support Nginx's auth_request

### ISSUE THREAD

**Issue by mbland** [bitly/oauth2_proxy#152]
I recently discovered the [Nginx `auth_request` directive](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html), which allows a setup like this:

```
server {
  listen 443 ssl spdy;
  server_name  myservice.com;

  include ssl/star.myservice.com.conf;

  location = /auth {
    internal;
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header X-Original-URI $request_uri;
  }

  location / {
    auth_request /auth;
    ...
  }
}
```

Would you be open to having me add an `/auth` endpoint or similar to the oauth2_proxy?

It'd basically involve splitting the authentication logic from `func (p *OauthProxy) Proxy(rw http.ResponseWriter, req *http.Request)` into a new `AuthenticateRequest()` function, adding a thin `AuthenticateOnly()` handler, and registering that with `func (p *OauthProxy) ServeHTTP(rw http.ResponseWriter, req *http.Request)` (and adding the requisite options, of course).

**Comment by mbland** [comment]
Per #153, the implementation turned out to be even less complicated than I expected. Got to reuse the test fixture from the existing `ProcessCookieTest`s as well.

**Comment by ishamfazal** [comment]
hey this comment isn't relevant for this issue, i'm running into a problem so would need some help to check if its on my code side or not i have created a new provider and trying to authorize so once the once the authorization code is sent back to call back url i get an error check the image 
![screen shot 2015-10-12 at 5 43 22 pm](https://cloud.githubusercontent.com/assets/11960696/10427645/da387dd2-7108-11e5-8fdd-d49bcdd8cc5a.png)
