### ISSUE TITLE
Adding a new provider

### ISSUE THREAD

**Issue by ishamfazal** [bitly/oauth2_proxy#155]
Hey,
Is there a default format(code) to add a new provider?

**Comment by mbland** [comment]
There's a pointer to the `providers` package at the very end of the README: https://github.com/bitly/oauth2_proxy#adding-a-new-provider

**Comment by ishamfazal** [comment]
yes i have defined my provider and set everything but i get this error even though the activation code sent back is correct it gives an error check the image, am i missing something ? 
![screen shot 2015-10-14 at 10 44 08 am](https://cloud.githubusercontent.com/assets/11960696/10475447/6014fd96-7261-11e5-8ab5-bc77b3926386.png)
