### ISSUE TITLE
google authentication: syntax error: sequence truncated

### ISSUE THREAD

**Issue by ArnaudT** [bitly/oauth2_proxy#176]
Hi,

I am using the latest master version from the 26-11-2015. I want to use the master version because I am interested with the -google-group support.

Here my command:
```
  exec  /usr/local/bin/oauth2_proxy -client-id="TEST.apps.googleusercontent.com" -client-secret="TEST" -upstream="http://0.0.0.0:8081" -cookie-secret="TEST" -email-domain="domain.com" -pass-host-header="true" -cookie-domain="domain.com" -http-address="0.0.0.0:4180" -google-group="access-tools@domanin.com" -google-admin-email="daniel@domain.com" -google-service-account-json="/opt/testapps.googleusercontent.com.json"
```

I have the following error when I log in:
```10.0.100.67 - - [27/Nov/2015:10:21:19 +0000] stage-internal.domain.com GET - "/oauth2/start?rd=%2F" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36" 302 334 0.000
2015/11/27 10:21:27 google.go:191: error fetching user: Get https://www.googleapis.com/admin/directory/v1/users/arnaud%40domain.com?alt=json: private key should be a PEM or plain PKSC1 or PKCS8; parse error: asn1: syntax error: sequence truncated
2015/11/27 10:21:27 oauthproxy.go:494: 127.0.0.1:48516 ("10.0.100.67") Permission Denied: "arnaud@domain.com" is unauthorized
2015/11/27 10:21:27 oauthproxy.go:316: ErrorPage 403 Permission Denied Invalid Account```

Do you have any idea of what can be wrong in my configuration?

If I remove -google-group, -google-admin-email and -google-service-account-json everything works fine.

Thanks.

Arnaud.

**Comment by jehiah** [comment]
`private key should be a PEM or plain PKSC1 or PKCS8; parse error: asn1: syntax error: sequence truncated` indicates you have an issue validating TLS for `www.googleapis.com`. Typically this is automatically loaded from one of the files referenced [here](https://github.com/golang/go/blob/master/src/crypto/x509/root_linux.go#L8-L13) and is provided by the `openssl` package.

Can you confirm you have such a file, and that it's valid?

**Comment by ArnaudT** [comment]
Thanks for your response.
Yes I have the following file `/etc/ssl/certs/ca-certificates.crt`.
but you right, it seems not valid has it has expired.

```openssl verify /etc/ssl/certs/ca-certificates.crt
/etc/ssl/certs/ca-certificates.crt: C = AT, O = A-Trust Ges. f. Sicherheitssysteme im elektr. Datenverkehr GmbH, OU = A-Trust-nQual-03, CN = A-Trust-nQual-03
error 10 at 0 depth lookup:certificate has expired
OK ```

I've tried to use update-ca-certificates but it didn't change the certificate status.

**Comment by ArnaudT** [comment]
Hi,
I can not find a way to update the following certificate `/etc/ssl/certs/ca-certificates.crt`.
I am using `Linux ip-10-0-101-36 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

I will find another way to manage group.

Thanks for your help.

**Comment by sellers** [comment]
You can also get this message if the JSON object that you are passing is wrong or is missing the certificate.  It will suggest the certificate is in ARN1 format but it is really missing.
