### ISSUE TITLE
Use email in X-Forwarded-User

### ISSUE THREAD

**Issue by nordicdyno** [bitly/oauth2_proxy#180]
Sometimes it would be more useful to pick Email instead of Username from oauth provider(s) as `X-Forwarded-User`.

Reason 1: Email is more unique
Reason 2: Actually I need backward compatibility for [my proxy implementation](https://github.com/nordicdyno/jenkins-goauth2). After that I can abandon support of it and switch on this amazing proxy ;)

**Comment by jehiah** [comment]
@nordicdyno `oauth2_proxy` already provides the header `X-Forwarded-Email`, so it's not completely clear to me exactly what you are proposing.

**Comment by nordicdyno** [comment]
I just want forward email as 'user name' to backend services. I think it requires code like:

    if AuthEmailAsUser {
        req.Header["X-Forwarded-User"] = []string{session.Email}
    }

I've tried `oauth2_proxy` in my environment today and was recognized by Jenkins as `nordicdyno` instead of nordicdyno@gmail.com (that I actually need)

**Comment by nordicdyno** [comment]
Oh, sorry! I see. Jenkins is flexible enough to redefine «Header User Name» to any header name.

Maybe other software can be not so flexible? just guessing

**Comment by jehiah** [comment]
@nordicdyno Thanks for opening this issue. I'm going to close it as you were able to successfully leverage the existing `X-Forwarded-Email` header.
