### ISSUE TITLE
Remap username against Ldap

### ISSUE THREAD

**Issue by eriste** [bitly/oauth2_proxy#185]
We're using Google to do oauth2 SSO to an internal service and Ldap to fetch information about group memberships etc. The problem is that some of our users have different Ldap uids and Google email addresses (without domain part), ex eriste != erik.stenvall.

To solve this I propose to have the oauth2_proxy make an Ldap call, searching for a matching email address and then substitute the values X-Forwarded-User and X-Forwarded-Email with the values retrieved from Ldap.

I have implemented it, seems to work, are you interested in the code?

/Ess

**Comment by jehiah** [comment]
see comment in #190
