### ISSUE TITLE
Why redirect via state parameter ?

### ISSUE THREAD

**Issue by r4um** [bitly/oauth2_proxy#189]
This essentially turns oauth2_proxy into an open redirector. 

As per the [RFC](https://tools.ietf.org/html/rfc6749#section-3.1.2.2) since we already have a registered redirection URI, do we really need to redirect
based on state parameter ?

**Comment by jehiah** [comment]
@r4um the redirection based on the state variable and should be limited to paths on the same domain, so it shouldn't be an "open" redirector.

If a user lands on page A (le'ts say `/page/a` ) and is unauthorized, they get the sign in page as expected. To complete the oauth flow with an authentication provider, the authentication provider will send the browser back to `https://$domain/oauth2/callback` which is the registered redirect URI. We want to send the user back to `/page/a` though, so we use `state` to track where they were when they started the oauth flow, and we send the browser back to that page.

Does that help clarify things for you?

**Comment by r4um** [comment]
The problem is it redirects to any http://somesite.com, if it is set by the state param (state=http://somesite.com). I don't see any check in the code where it ensures state is in `$domain`.

**Comment by r4um** [comment]
Does the following patch look meaningful to not accept any host in the state param ? I'll send a PR if it is.

```diff
diff --git a/oauthproxy.go b/oauthproxy.go
index dd69d6a..8aff9a9 100644
--- a/oauthproxy.go
+++ b/oauthproxy.go
@@ -478,6 +478,17 @@ func (p *OAuthProxy) OAuthCallback(rw http.ResponseWriter, req *http.Request) {
        redirect := req.Form.Get("state")
        if redirect == "" {
                redirect = "/"
+       } else {
+               redirect_uo, err := url.Parse(redirect)
+
+               if err != nil {
+                       p.ErrorPage(rw, 400, "Bad state URL", "Bad Request")
+                       return
+               }
+               if redirect_uo.Host != "" {
+                       p.ErrorPage(rw, 400, "Bad state URL", "Bad Request")
+                       return
+               }
        }

        // set cookie, or deny
```

**Comment by jehiah** [comment]
@r4um an appropriate check at that point would just be ignoring `state` if it is present but does not start with `"/"`. That would match the check [here](https://github.com/bitly/oauth2_proxy/blob/master/providers/provider_default.go#L87-L89) at the start of the oauth flow.

**Comment by r4um** [comment]
Thanks, filled #194.
