### ISSUE TITLE
Support split-horizon DNS for an arbitrary number of upstreams

### ISSUE THREAD

**Issue by therc** [bitly/oauth2_proxy#192]
Suppose you have N internal hosts you want to expose with just one proxy instance.
If you have a split-horizon DNS setup, you can make all external lookups return the same public address of the instance. Internally, they return distinct IP addresses, e.g. in the 10.* range.

How would you support this, without listing all the internal hosts as upstreams? Assume the list keeps changing.

One way to do it would be to have some special upstream syntax, perhaps http[s]?://(:PORT) (empty hostname), which tells the proxy to fill in the blank with whatever the Host: header was. It will then do a DNS lookup and it will talk to the right host.

On the other hand, someone might craft special requests to the proxy IP address with arbitrary names that are not in the public DNS entries, trying to access additional hosts (yes, we are proxying authenticated credentials, but let's assume the worst for a second). Perhaps the upstream syntax, then, should rather be some kind of regex instead.

**Comment by jehiah** [comment]
@therc interesting questions. There is always going to be some limitation in native routing that `oauth2_proxy` provides. Fortunately this is the benefit of HTTP as it's easy to layer systems (And really, this is exactly what `oauth2_proxy` was created for: adding "just" an authentication layer).

In your case i would probably use `oauth2_proxy` in front of `nginx`, and in `nginx` I would handle routing to the N valid upstreams and do matching on the list of known valid hostnames, etc. I've also seem some newer tools that are designed to give easier "dynamic" config like [gogeta](https://github.com/arkenio/gogeta) that might be a fit if you know the list of upstreams might change frequently.

**Comment by therc** [comment]
In my case, there's already something else in front of the proxy, the upstreams have their own internal load balancing and, although the list might change frequently, names are predictable and easily matched by a regex, so I'd rather not add yet another moving part. Would you be interested if I sent a PR with no more than a few extra lines in the actual serving path?

**Comment by jehiah** [comment]
@therc thanks again for opening this issue. I've been thinking about it a bit and i think i'm going to close it, as i don't want the configuration for upstreams to get too complicated, and i think introducing regexes on the host or full upstream would do that.

I think your best bet if your hostnames are fairly predictable and can be fetched from an external state is to make a shell script that regenerates your oauth2_proxy config file upstream block and restarts oauth2_proxy to keep it's config current. If you do need to regex match your hostnames, i suggest passing traffic through something like nginx after oauth2_proxy (even though you described you also have something, possibly nginx, before oauth2_proxy. layers all the way down). 

cheers

**Comment by jehiah** [comment]
@therc It just occurred to me that your config might be better served by using the `ouath2_proxy` built in support for Nginx [auth requests](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html)
