### ISSUE TITLE
Can upstream be a remote server? - Debug request

### ISSUE THREAD

**Issue by hhsnopek** [bitly/oauth2_proxy#203]
I'm attempting to use `oauth2_proxy` to put a authentication wall up in front of a static site that is hosted else where. I'd like the upstream to be the remote site or be able to continue onto the remote site via `proxy_set_header Host remote.site.com;`

Here's my current nginx conf:
```
server {
    listen 80;
    server_name app.example.com;

    location / {
        proxy_pass http://127.0.0.1:4180;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_connect_timeout 1;
        proxy_send_timeout 30;
        proxy_read_timeout 30;
    }
}
```

My upstream is set to `"http://app2.example.com/"`, after authentication thru Google I return to my callback and receive a 404... looking at the logs I never get past:
```
/oauth2/start?rd=%2F
```
**Note** the callback returns to `example.com/oauth2/callback` instead of `app.example.com/oauth2/callback`

**Comment by ploxiln** [comment]
Assuming app2.example.com depends on the Host header to be reached, you'll want to set `--pass-host-header=false` for oauth2_proxy so it uses the host of the upstream url for the Host header.

If you don't also use `--signature-key=...` to sign requests to the remote upstream, and validate those requests on the upstream side, then the remote upstream would be vulnerable to direct access from users without going through oauth2_proxy. Just FYI :)

**Comment by hhsnopek** [comment]
@ploxiln thank you, but since yesterday i've updated my nginx (wasn't able to get `oauth2_proxy` to work in that scenario)... 

I have multiple apps now and considering I can pass the host header, I should be able to reach the original `proxy_pass` specified in each subrequest... tho `oauth2_proxy` isn't even being touched/routed to. (sorry for the lack of nginx knowledge, learning as I go here). Is this a better solution than my previous, if not how do I go about accomplishing the task below?

```
server {
    listen 80;
    server_name ~^(?<subdomain>.+)\.example\.com;

    auth_request /auth;
    location = /auth {
        proxy_pass http://127.0.0.1:4180;
        ...
    }

    rewrite ^ /$subdomain

    location /app {
        proxy_pass app2.example.com;
    }

    location /another_app {
        proxy_pass another_app2.example.com;
    }
}

**Comment by ploxiln** [comment]
Every request needs to go through oauth2_proxy to get to the app. oauth2_proxy is intended to proxy all the requests to the app to make sure they are all authorized.

To handle multiple apps, you have a few options.
  * multiple instances of oauth2_proxy, one per upstream, listening on different ports. nginx chooses the oauth2 proxy based on the host header
  * multiple upstreams configured in the oauth2_proxy, if they have unique prefix path components
  * use nginx auth_request directive for every request instead of proxying

that said, issues here are for oauth2_proxy bugs, not nginx help (or general web security help) :)

**Comment by hhsnopek** [comment]
haha understood, let me rephrase my question, I know in the last example in the `readme.md` uses `auth_request`, I'm suppose to handle the `/oauth2/callback` not `oauth2_proxy` correct?

**Comment by ploxiln** [comment]
I'm not familiar with auth_request myself, but the example at the bottom of Readme.md looks incomplete. First, the default auth endpoint is `/oauth2/auth`, not `/auth`, and you would likely need to proxy all of `/oauth2/*` to oauth2_proxy so it could handle the callback etc. Finally, for the 401 error page, you should probably use or redirect to `/oauth2/sign_in`. Again, I'm not really familiar with this technique, just making educated guesses :) I'd suggest one of the other options, they're simpler.

**Comment by hhsnopek** [comment]
I was stumped on that for a while, thank you very much! :smile:
