### ISSUE TITLE
X-Forwarded-User should be configurable independent of -pass-basic-auth option

### ISSUE THREAD

**Issue by omazhary** [bitly/oauth2_proxy#205]
We are using oauth2_proxy in front of [grafana](http://docs.grafana.org/installation/configuration/#authproxy) with its "auth.proxy" configuration option. This relies on X-Forwarded-User header to be sent.
However if we use option `-pass-basic-auth`, we not only get X-Forwarded-User but also Authorization: Basic with the base64-encoded username and an empty password. This will fail the login to grafana.

Instead, we want to be able to only send X-Forwarded-User (and X-Forwarded-Email) independent of BASIC auth.
Will provide a patch soon.

**Comment by johnrengelman** [comment]
+1 Just smashed into this exact issue as well. Changes LGMT.

**Comment by johnrengelman** [comment]
Was just trying this patch out, but there still doesn't seem to be a way to log in to Grafana with Basic Auth once this proxy is in front of it (maybe that makes sense), but I'm trying to get at the built in admin account, but I always get redirected back to my oauth login.

**Comment by omazhary** [comment]
Hi John, our scenario only relied on OAuth authentication, that's why we chose this proxy. It performs the authentication with grafana in the background and then logs you in directly to the dashboards. Making the regular grafana login page accessible would make the login process a little confusing.

Regarding the built-in admin account, you should be able to login using the UAA admin, as long as it is the exact same as the one in grafana. That is a bug, but has nothing to do with the proxy. This is basically because grafana calls its default administrator "admin", as well as the UAA. And, since grafana only matches the usernames, you can use any "admin" user to login to the grafana super-user. Ideally, this user should be changed in grafana, by being assigned a different username, either as a default, or by whoever is responsible for installing the system. Then, the new user would have to be created in cloud foundry's UAA as well.

**Comment by johnrengelman** [comment]
Got it.

Definitely a bit annoying. Not really an issue with this tool, but was unexpected. Would be nice if Grafana had a property to promote specific accounts to admin on creation. Anyway, I worked around it, but bypassing the proxy, then logging in with the admin account and promoting my OAuth account to be an admin.

Thanks for the pointers.

**Comment by omazhary** [comment]
No problem ;)

**Comment by grahamrhay** [comment]
I have the same problem in front of Jenkins, the basic auth header causes the reverse proxy plugin to error, but I need the X headers. It would be great if this was merged.

**Comment by zlatkoc** [comment]
Same issue with Jenkins as @grahamrhay reported. 

Please merge this. Thanks!

**Comment by FrederikNS** [comment]
@jehiah would it be possible to get this merged?
