### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by gkuchta** [bitly/oauth2_proxy#209]
Hi,

The ability to use Enterprise GIT is a pretty compelling feature. Any chance you could bundle a new release? Lost some time this afternoon trying to figure out why my validate_url params, etc, weren't being respected until I compared the feature-addition PR to the release date. Can build my own, but it might save some confusions for other folks.

Anyhow, handy bit of kit! Thanks for your work!

Cheers,

Garrett

**Comment by ploxiln** [comment]
dup of #193

**Comment by jehiah** [comment]
yes yes, we do need a new release. noted =)
