### ISSUE TITLE
Suffix ignored after path when proxifying?

### ISSUE THREAD

**Issue by raphink** [bitly/oauth2_proxy#215]
When setting an upstream such as `http://hello/foo/bar/`, all requests *starting* with `/foo/bar/` are redirected to `http://hello/`.

For example, `http://<mydomain>/foo/bar/logo.png` displays the content of `http://hello/`, not `http://hello/logo.png`.

Is that normal?

**Comment by ploxiln** [comment]
The request to `http://<mydomain>/foo/bar/logo.png` is proxied to `http://hello/foo/bar/logo.png` (but it will keep the original `<mydomain>` Host header unless configured otherwise). Your app is likely not expecting such a request :)

**Comment by raphink** [comment]
OK that makes more sense. Is there a syntax to proxy `/foo/bar/` to `/` as described in my initial question?

**Comment by ploxiln** [comment]
I don't think there is such syntax or option. You'll want to get something like nginx involved in your setup.

**Comment by raphink** [comment]
Right, or haproxy... But then I'll need to have one oauth2_proxy for each backend I guess, since nginx/haproxy would be doing the routing...

**Comment by ploxiln** [comment]
yup - or: web -> oauth2_proxy -> nginx/haproxy -> backends

**Comment by raphink** [comment]
But then oauth2_proxy would have to be the SSL termination

**Comment by ploxiln** [comment]
oauth2_proxy can do ssl termination. But, I've acutally done this before:
internet -> nginx 0.0.0.0:443 -> oauth2_proxy -> nginx 127.0.0.1:8000 -> files/upstreams
(same nginx process, two different server blocks in the config)

**Comment by raphink** [comment]
I see. I'll have to look into that as I want to use oauth2_proxy add as generic auth service in rancher.

**Comment by ploxiln** [comment]
I suggest closing as #notabug
