### ISSUE TITLE
Binaries built using Go 1.5.3 to address TLS security issue

### ISSUE THREAD

**Issue by mattbostock** [bitly/oauth2_proxy#221]
go1.5.3 (released 2016/01/13) [includes a security fix](https://golang.org/doc/devel/release.html) to the math/big package affecting the crypto/tls package, which could affect anyone using oauth2_proxy with TLS enabled.

It might be prudent to release new binaries using Go 1.5.3 to address the issue. Anyone could build their own binaries in the meantime to workaround.

**Comment by jehiah** [comment]
Thanks @mattbostock going to mark this as a duplicate of #193 I've been busier than expected, but this isn't forgotten

**Comment by mattbostock** [comment]
Thanks @jehiah :+1:
