### ISSUE TITLE
'/' redirect check isn't enough.

### ISSUE THREAD

**Issue by sdier** [bitly/oauth2_proxy#228]
'//foo.com/foo' is a valid url, so the redirect check at oauthproxy.go:479 is not sufficient for its intent.

Since I'm using this hole to redirect to other domains within a set of subdomains -- it would be cool if this was somehow preserved so I can have a partially open redirect.  (I'm using an 'auth' domain and redirect to it from other domains and then redirect back while using the nginx aut -- I plan on writing up the configuration soon for others to use.)

**Comment by rcoup** [comment]
@sdier can you share the config briefly?
