### ISSUE TITLE
Cookie "_oauth2_proxy" not present

### ISSUE THREAD

**Issue by amlwwalker** [bitly/oauth2_proxy#238]
Hi, I've tried the following on both an SSL protected app on the server and a standard HTTP app. The configuration apart from that has been identical.

I start oauth2_proxy with: 

```
./oauth2_proxy -email-domain=gmail.com -upstream=http://internal.domain.com -cookie-secret=whatthe -client-id=xyxyxyxyxy.apps.googleusercontent.com -client-secret=somesecret -redirect-url=http://internal.domain.com/oauth2/callback
```

At this point, I think its important to mention I am not entirely sure what the difference between the upstream URL is and the redirect-url. However I don't think it is those causing me my problem. What I do think is the case is they need to match the config in the Google Auth Dashboard configuration and therefore they can't be http://localhost/.......

My nginx configuration for the two apps I have tried (one behind SSL) looks like this:

```
server {
	listen       80/443;
	server_name  internal.domain.io;
	location = /auth {
		internal;
		proxy_pass http://127.0.0.1:4180/; #oauth2_proxy
	} 
    location / {
        auth_request /auth;
        proxy_pass  http://127.0.0.1:5000/; #the app
    }
}
```

What I understand then is that every request will have to go through /auth. If oauth2_proxy has a valid cookie for this user then they will be passed on to the upstream url. If it doesn't have a valid cookie then they will be asked to authenticate.

What I am experiencing is a 403 error all the time (I don't get sent to google auth) and in the logs of oauth2_proxy I can see

```
oauthproxy.go:455: 127.0.0.1:53207 Cookie "_oauth2_proxy" not present
```

I think I am not passing a cookie in the nginx correctly to the `/auth` location. Any help would be massively appreciated. Thanks

**Comment by ploxiln** [comment]
The "nginx auth_request" mode documentation is very poor - it's incomplete and, basically, wrong. If you're proxying to a single application, just proxy, don't auth_request.

see #169 and https://github.com/bitly/oauth2_proxy/issues/203#issuecomment-180555655

**Comment by amlwwalker** [comment]
OK thanks, thats good knowledge...

I have adjusted Nginx so that my location block now looks like:

```
location / {
       proxy_pass http://127.0.0.1:4180/;
}
```

which means that I do now see oauth2_proxy when I hit the url. Thats good. 

I am starting it with 

```
./oauth2_proxy -email-domain=gmail.com -upstream=http://localhost:3000 -cookie-secret=whatthe -client-id=xxx.apps.googleusercontent.com -client-secret=xxx -redirect-url=http://internal.app.com/oauth2/callback
```

So I suppose my question is now have I got the upstream right for a local app and the -redirect-url for google auth?

I do indeed get carried through to google auth, it asks for offline access:

![image](https://cloud.githubusercontent.com/assets/2920180/14600428/6f821c60-0554-11e6-9ff0-1167f8097e49.png)

However that takes me back to oauth2_proxy login and I can see in the logs that the user is auth'd but the cookie isn't present:

> 2016/04/18 09:58:44 127.0.0.1:4180 GET - "/oauth2/start?rd=%2F" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36" 302 326 0.000

> 2016/04/18 09:58:51 oauthproxy.go:435: 127.0.0.1:53285 authentication complete Session{me@gmail.com token:true expires:2016-04-18 10:58:51 +0000 UTC refresh_token:true}

> 127.0.0.1 - - [18/Apr/2016:09:58:51 +0000] 127.0.0.1:4180 GET - "/oauth2/callback?state=/&code=4/xxxx" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36" 302 24 0.261

> 2016/04/18 09:58:51 oauthproxy.go:455: 127.0.0.1:53286 Cookie "_oauth2_proxy" not present

> 127.0.0.1 - - [18/Apr/2016:09:58:51 +0000] 127.0.0.1:4180 GET - "/" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36" 403 2284 0.000

Its close but that cookie isn't being passed through!

**Comment by amlwwalker** [comment]
I found the answer to this. Hopefully it will help anyone else.

My final nginx configuration looks like this. Adding the proxy information seemed to solve the passing of the cookie:

```
server {
	listen       80;
	server_name  internal.website.io;

    location / {
	    proxy_pass http://127.0.0.1:4180;
            proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Scheme $scheme;
	    proxy_connect_timeout 1;
	    proxy_send_timeout 30;
	    proxy_read_timeout 30;
	}
	server_tokens off;

}
```

Then to start oauth2_proxy I used:

```
./oauth2_proxy -email-domain=gmail.com -upstream=http://127.0.0.1:5000 -cookie-secret=somesecret -client-id=googleid.apps.googleusercontent.com -client-secret=googlesecret -provider=google -cookie-secure=false
```

Can we add this to the readme?

**Comment by chinchang** [comment]
Just a note on this: you might have to delete you exisiting HTTPS only cookies before login again.
