### ISSUE TITLE
Allow routing based more fine graned routing

### ISSUE THREAD

**Issue by johanhaleby** [bitly/oauth2_proxy#255]
It's possible to route based on path today but I'ld like path "/x" to route to "http://something.com/y". This this something that could be supported?

**Comment by ploxiln** [comment]
Just my 2c:

oauth2_proxy should not gain additional features which are provided by other http proxies like nginx. Just recommend: nginx port 80/443 -> oauth2_proxy port 4180 -> nginx (other port e.g. 8080), all special routing can go in the innermost nginx server block config.

**Comment by sylr** [comment]
I'm with @johanhaleby here, multiplying layers of reverse proxy is painful.

I'd like oauth2_proxy to be able to chose an upstream based on the request url path.

Cheers.

**Comment by jehiah** [comment]
@sylr `oauth2_proxy` does choose an upstream based on the request url path; you can register multiple upstreams on different paths. `oauth2_proxy` will not rewrite the path. If you need fine grained request handling like that you'll need to use some other tool in combination with oauth2_proxy.
