### ISSUE TITLE
Not respecting pass_basic_auth = false

### ISSUE THREAD

**Issue by NeckBeardPrince** [bitly/oauth2_proxy#283]
Even when turning off pass_basic_auth oauth seems to still be passing X-Forwarded-User and X-Forwarded-Email information to upstream

**Comment by ploxiln** [comment]
`pass_basic_auth` only refers to the `Authentication: Basic <base64 of user:pass>` header, for upstream applications that can already use the username from it. The X-Forwarded- headers are always sent as a convenience.

As-Designed :)

**Comment by ploxiln** [comment]
It looks like I was totally wrong about that ... I just assumed it did what you complained ... but it looks like the code does only set those headers if pass-basic-auth is enabled, and has for a long time.
https://github.com/bitly/oauth2_proxy/blob/master/oauthproxy.go#L600
