### ISSUE TITLE
Removing login prompt

### ISSUE THREAD

**Issue by Totolin** [bitly/oauth2_proxy#284]
Is there any possibility to remove the webpage that prompts you to log in using the provider set in the configuration? It really has no purpose if you have only one provider, and it should redirect straight to the oauth provider's page.

Is there an option to do this, or have I missed it in the documentation?

**Comment by ploxiln** [comment]
`--skip-provider-button`
https://github.com/bitly/oauth2_proxy/blob/2fa0a35c7f89706ddf9dff3e6956a1af8b937066/main.go#L39

**Comment by reist** [comment]
In case of using Nginx's auth_request, should the /oauth2/sign_in be switched to /oauth2/start to get the same effect? Based on a couple of checks, it seems to be working as long as the _oauth2_proxy cookie didn't timeout.

**Comment by Alives** [comment]
This option isn't working for me.  I only have Google configured as a provider, and I still see the "Sign in with a Google Account" button page if I don't have the oauth cookie set properly.
