### ISSUE TITLE
Retrieving logged in user from resulting application

### ISSUE THREAD

**Issue by amlwwalker** [bitly/oauth2_proxy#300]
Hi

When I login with this to my server, is there anyway of passing the username/email address in some way to the web app the user ends up in, or is it necessary for the user to log in again to the end app to get a login?

**Comment by igroykt** [comment]
@amlwwalker there is option -pass-basic-auth=true: pass HTTP Basic Auth, X-Forwarded-User and X-Forwarded-Email information to upstream.
If your app work on php then check phpinfo() for global variable _SERVER['X-Forwarded-User/Email'].
By the way this is just a guess.
