### ISSUE TITLE
iOS 9.x = cookie not present

### ISSUE THREAD

**Issue by igroykt** [bitly/oauth2_proxy#304]
Hi all!
Strange thing. When i login from iOS 9.x then in logs i see "cookie not present" and redirecting to login page because of 403 error, but iOS 8.x work fine.
Safari settings->accept cookies from visited.
oauth config:
http_address = "127.0.0.1:4181"
#https_address = "127.0.0.1:443"
#tls_cert_file = ""
#tls_key_file = ""
redirect_url = "https://my.domain.com/oauth2/callback"
upstreams = [
     "https://my.domain.com"
]
request_logging = true
pass_basic_auth = true
client_id = "my_id"
client_secret = "my_secret"
provider="google"
authenticated_emails_file = "/etc/oauth2_proxy/access.eml"
cookie_name = "my.domain.com"
cookie_secret = "some_secret"
cookie_domain = "my.domain.com"
cookie_expire = "3h"
#cookie_refresh = ""
cookie_secure = true
cookie_httponly = true

nginx location config:
        location / {
                proxy_pass http://127.0.0.1:4181;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Scheme $scheme;
        }

Anyone?

**Comment by igroykt** [comment]
Updated from 9.3.3 to 9.3.5. No success.

**Comment by jehiah** [comment]
@igroykt you have `cookie_secure=true` which is good, but can you make sure you are accessing "https://my.domain.com/` in both tests? 

If that isn't the issue, logs showing successful auth, and then the request which is missing cookie (w/in the configured cookie_expire) would be helpful.

**Comment by igroykt** [comment]
@jehiah 
======ios 8=========
188.244.138.105 - - [09/Sep/2016:08:20:54 +0900] "GET /PROJECT/SomeFile.ipa HTTP/1.1" 302 154 "-" "itunesstored/1.0 iOS/8.4 model/iPad3,3 build/12H143 (5; dt:78)" "-"
188.244.138.105 - - [09/Sep/2016:08:26:37 +0900] "GET /index.php?path=/PROJECT/SomeFile.ipa HTTP/1.1" 200 128999754 "-" "itunesstored/1.0 iOS/8.4 model/iPad3,3 build/12H143 (5; dt:78)" "-"
=======ios 9========
188.244.138.105 - - [09/Sep/2016:08:28:29 +0900] "GET / HTTP/2.0" 403 1161 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G34 Safari/601.1" "-"
188.244.138.105 - - [09/Sep/2016:08:28:31 +0900] "GET /oauth2/start?rd=%2F HTTP/2.0" 302 634 "https://my.host.com/" "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0
======================
Yes in both tests backend was on apache with ssl.

**Comment by igroykt** [comment]
Oauth log:
=========ios8==============
2016/09/09 10:32:02 oauthproxy.go:526: 127.0.0.1:33596 ("myip") Cookie "my.domain.com" not present
myip - - [09/Sep/2016:10:32:02 +0900] my.domain.com GET - "/" HTTP/1.0 "Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H143 Safari/600.1.4" 403 2244 0.000
myip - - [09/Sep/2016:10:32:05 +0900] my.domain.com GET - "/oauth2/start?rd=%2F" HTTP/1.0 "Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H143 Safari/600.1.4" 302 326 0.000
2016/09/09 10:32:55 oauthproxy.go:485: 127.0.0.1:33615 ("myip") authentication complete Session{myacc@domain.com token:true expires:2016-09-09 11:32:55 +0900 YAKT refresh_token:true}
myip - - [09/Sep/2016:10:32:55 +0900] my.domain.com GET - "/oauth2/callback?state=/&code=4/jejg5FdidynMAO7ic0ZqyZ9sAXOEsbLIXReA71--YUI" HTTP/1.0 "Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H143 Safari/600.1.4" 302 24 0.177
myip - myacc@domain.com [09/Sep/2016:10:32:56 +0900] my.domain.com GET my.domain.com "/" HTTP/1.0 "Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H143 Safari/600.1.4" 200 1614 0.042

==========ios9=============
myip - - [09/Sep/2016:10:33:10 +0900] my.domain.com GET - "/oauth2/start?rd=%2F" HTTP/1.0 "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1" 302 326 0.000
2016/09/09 10:33:14 oauthproxy.go:485: 127.0.0.1:33635 ("myip") authentication complete Session{myacc@domain.com token:true expires:2016-09-09 11:33:14 +0900 YAKT refresh_token:true}
myip - - [09/Sep/2016:10:33:14 +0900] my.domain.com GET - "/oauth2/callback?state=/&code=4/5oBK5THTgw9BWhak1o_kotpkKaoBjfIVwZI0BRZCfd0" HTTP/1.0 "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1" 302 24 0.174
2016/09/09 10:33:14 oauthproxy.go:526: 127.0.0.1:33636 ("myip") Cookie "share.mytona.com" not present
myip - - [09/Sep/2016:10:33:14 +0900] my.domain.com GET - "/" HTTP/1.0 "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1" 403 2244 0.000

**Comment by igroykt** [comment]
New version of oauth didn't helped.

**Comment by igroykt** [comment]
@jehiah here is some info from charles session:

> :method: GET
:scheme: https
:path: /oauth2/start?rd=%2F
:authority: my.domain.com
accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1
accept-language: ru
referer: https://my.domain.com/
accept-encoding: gzip, deflate

> :method: GET
:scheme: https
:path: /oauth2/callback?state=/&code=4/7EPabO9EsuVUpbMf51CVp0uhaqpwVJSac-TCyffaLyg
:authority: my.domain.com
accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1
accept-language: ru
referer: https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&client_id=myid.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fmy.domain.com%2Foauth2%2Fcallback&response_type=code&scope=profile+email&state=%2F
accept-encoding: gzip, deflate

> :method: GET
:scheme: https
:path: /o/oauth2/auth?access_type=offline&approval_prompt=force&client_id=myid.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fmy.domain.com%2Foauth2%2Fcallback&response_type=code&scope=profile+email&state=%2F
:authority: accounts.google.com
cookie: ACCOUNT_CHOOSER=AFx_qI5aCH_pdRe6clx97K6Sh_pHF8rsKWCJVQhO9FVqJOJBDAVTQTklqDUDg_vYnfmy8Dh1Iua_Kr_jnhQVXKrc2GHfjlnaPzCnigpJH2_oeF9Ihx10od1OJ7bgu0-DzXhv_EQAtnMc; GAPS=1:jzuqVZtznpnua9HPwPP5ySIULyDZlQ:3WaIvrXhYTvD4A0w; LSID=s.RU|s.youtube:vANoM1wnXPY4X0E-UQMOxvNbGxzgoLi_0CjUf4cUsLyG5grgBD_zsPhjXsOlBgH59RqX5A.; SMSV=ADHTe-DDHzTi2b-cOwL6fvE-itNtYVuCoDAN9HoiwrvneugtzQIUizxbXq-dcCcX0-9F6gWAe0Cd6juMr9nTZuaEN5LAyGnj1KjgqyTuXmue75aXbget1gsb954sGeqLMSqgFuWTK1tJ; APISID=defIIYHxvsVx1fOs/AWY9qUQXAi1z_yc3M; HSID=Ah1SkUYjQRk3uLwiw; NID=86=bJuK_RxOtb_CoPwTFADsPHDrV47wENB8X90qlyASk1ZGKSP4qjcFBIgQ4S6XpD83GNmkCE3EoUcLSSmi1QrNk1nqo6sj4PNXWAJTqtaPQHCtCuKvyxm76b_TyRc3zordjjGf_GJeMER0v1axTzz2z0qkLS4p; SAPISID=9eTPlz5nKyTlOkX9/AvHfdBRZbovgFvX3c; SID=sid.; SSID=ssid
accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1
accept-language: ru
referer: https://my.domain.com/
accept-encoding: gzip, deflate

> :method: POST
:scheme: https
:path: /o/oauth2/approval?hd=domain.com&as=482580c477f6fd67&pageId=none&xsrfsign=AHPwt88AAAAAV9YWadR77sj5E6yJ2fW0Dg-yFxSke29D
:authority: accounts.google.com
accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
content-type: application/x-www-form-urlencoded
origin: https://accounts.google.com
cookie: ACCOUNT_CHOOSER=AFx_qI5aCH_pdRe6clx97K6Sh_pHF8rsKWCJVQhO9FVqJOJBDAVTQTklqDUDg_vYnfmy8Dh1Iua_Kr_jnhQVXKrc2GHfjlnaPzCnigpJH2_oeF9Ihx10od1OJ7bgu0-DzXhv_EQAtnMc; GAPS=1:jzuqVZtznpnua9HPwPP5ySIULyDZlQ:3WaIvrXhYTvD4A0w; LSID=s.RU|s.youtube:vANoM1wnXPY4X0E-UQMOxvNbGxzgoLi_0CjUf4cUsLyG5grgBD_zsPhjXsOlBgH59RqX5A.; SMSV=ADHTe-DDHzTi2b-cOwL6fvE-itNtYVuCoDAN9HoiwrvneugtzQIUizxbXq-dcCcX0-9F6gWAe0Cd6juMr9nTZuaEN5LAyGnj1KjgqyTuXmue75aXbget1gsb954sGeqLMSqgFuWTK1tJ; APISID=defIIYHxvsVx1fOs/AWY9qUQXAi1z_yc3M; HSID=Ah1SkUYjQRk3uLwiw; NID=86=bJuK_RxOtb_CoPwTFADsPHDrV47wENB8X90qlyASk1ZGKSP4qjcFBIgQ4S6XpD83GNmkCE3EoUcLSSmi1QrNk1nqo6sj4PNXWAJTqtaPQHCtCuKvyxm76b_TyRc3zordjjGf_GJeMER0v1axTzz2z0qkLS4p; SAPISID=9eTPlz5nKyTlOkX9/AvHfdBRZbovgFvX3c; SID=sid.; SSID=ssid
content-length: 1334
user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1
referer: https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&client_id=myid.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fmy.domain.com%2Foauth2%2Fcallback&response_type=code&scope=profile+email&state=%2F
accept-language: ru
accept-encoding: gzip, deflate

bgresponse=%21hIelh6ZCOzKlLqUXPjNEqF9taILDA7kCAAAAHlIAAAAGCgAkbqQtaUIa-4IjKTGEUHod6KYi3q6BXXRj9SNVYjxA25mL6atzmQD8v0zrg7r64G5iTMt1YHTGeJHO0jIn0nazkIwXuficWqxb9xCUPpZoPteDlAevVjN2Ptk96X7NXGR3GfcpXWvf7At4U7U9oAxkH0JuIR_xd82E2SnP56BiMYH8vch5_pe85KnikfJww-ex-1l585WFWo-C6B0GSn_TGkSywkI1JnG0Nrh9rTbGAGaeqYmGYSXKpc1ctqiVy1rUtQxGl93uJRzIxONeVMJrajBpTu-Drk7pTGeVR4xXuCsj5fFvrRqY_hf9RNVXkZOtL3UqFWAr2OWVJDKzXpsd9Yku1zW8B1eydzdkBoAq3Uz1RavUOA8tfcXMoAUYMogPkhQl&_utf8=%E2%98%83&state_wrapper=Cs0EKkFILTFOZzJxMllvbkxjRTd0elNQSUQzT2E1TzZldGNOSDhXYk1wRjRLdHUzRmsydU40NjFRZkpuMHhrZlhyNzl3aU9WZGIwZXdxcXlFcWpJcmxtTi1uTGZ1VWt0WHZYcXlIYnZNZmwxNlFidUYtbmV0VmE3aERMVVJqYUYxbU1ESFlZajFFengwLWdqZkVFRUpkRnNDZUxtbjU3WTZGZlp4bENKSkFzN3VFY0xHT2R4bU1VMDV5WWttNUNjeDNSSWVOTWo5NXJ6X0hZQ3c5dGpzazVtNWg4VFBhQWE0RFZNZzlzUlFCS2xPRzJYOWR0bVFXaFhXV0dUUi1Cd3lCZHRvTUxZeEFSTHlCck16Ul9iZFJUX2ZBSmhUam9oVW92R0tqbnZ0SmFxOVZhWDlnandTcmctTDYtdWNKMm15SnFlbk9ETVBIOEtRd0x4dEhlUUVPZXdmdHNjX3lBSURaOTU4OFJqQUstM3JfLUNqWjFyMEVPM3RqWk5fQURNS1FJTExERmpORWg0VFB5eUwxbWs2WVYxYjlxVEpSMUdyb1c2Mk1tNUhkR0hNME5SYmhJT3VwMjNsN0ZlZ2ZrR1FNNlFaOFpoYzd3Z0NmNk5FdUQ1U2NyVUp3WXltUjY4b1NVWU1teTduRFpvemctZS0zNXhTN3RFdEw4bm1DcXZmRnlVWWVRUmwwY1lILWY2M3VvRTdZRkRVOEF3OUp2SlhZVTQ3QVc2bUFlaW8za1d1QmpRRC1VNGZ4UE9mLWpOd2pmYU0ybHZXdTNxRE9IVhIVMTAzNzU0MTA0MTIwMDQ1MzQwMjQxGMX5pNfnm6jbGw&submit_access=true

> CONNECT play.google.com:443 HTTP/1.1
Host: play.google.com
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1
Connection: keep-alive
Proxy-Connection: keep-alive


[ios_12_09_16.zip](https://github.com/bitly/oauth2_proxy/files/466426/ios_12_09_16.zip)

**Comment by igroykt** [comment]
Looks like cookies lost when redirecting from javascript with allow button to redirect url.
-skip-provider-button=false doesn't work?
oauth2_proxy v2.1

**Comment by igroykt** [comment]
pass_basic_auth = true makes json error instead of button render.
oauth2_proxy v2.2.0-alpha (built with go1.5.1)

**Comment by igroykt** [comment]
@jehiah Wether in the future features like force-login and set-cookie? So if we have no cookie then we can pass to upstream that will set some cookie then upstream request to localhost to make some checks before proxying to real backend.

**Comment by igroykt** [comment]
Seems like solved by updating to ios 9.4.x.
