### ISSUE TITLE
logout route

### ISSUE THREAD

**Issue by captncraig** [bitly/oauth2_proxy#306]
It would be somewhat useful to have a route I can go to to log out of the application. Sure I can delete the cookie in my proxied app, but then I have to configure the cooke name and so forth. Would be nice if I could just make a link to `/oauth2/logout` and let the proxy do the cookie clearing, then redirect me to the home page.

**Comment by jehiah** [comment]
@captncraig If you link to `/oauth2/sign_in` you will be signed out.  If you'd find it useful to have an additional path that signs you out and redirects to `/` I'd be happy to accept a PR that does that.
