### ISSUE TITLE
Does oauth2 proxy support REST API call authentication?

### ISSUE THREAD

**Issue by siningma** [bitly/oauth2_proxy#307]
We want to use oauth2 proxy with Google provider to authenticate all requests to our internal servers. Currently, oauth2 proxy can handle requests from web browsers.
But our Jenkins servers also need to make some GET API calls to our internal servers. These calls are also going through oauth2 proxy. But they cannot be authenticated by the proxy. The proxy rejects all requests and returns the initial login page in html.

Is there a way to configure oauth2 proxy so that the proxy can authenticate and accept client side REST API calls? If this is possible, what parameter or header do the client send in the request?

Many thanks.

**Comment by ploxiln** [comment]
use the `--htpasswd-file` option, have your service use a special username/password via basic auth
