### ISSUE TITLE
502 "operation was canceled" when user makes multiple requests thru oauth2_proxy

### ISSUE THREAD

**Issue by jeremybmerrill** [bitly/oauth2_proxy#316]
I'm using oauth2_proxy (latest version of `master`) to proxy to a fairly low-traffic internal server running nginx and serving some static files, along with a database. A single page-load requests about 30 files (JS assets, CSS, etc.). 

Sporadically, at least one of these ~31 request will fail; often multiple fail; occasionally, they all succeed. Refreshing the page several times eventually gets you a success, usually. Different requests that fail at different instances -- and the requests that fail can be to either upstream.

Expected behavior is that all completeable requests are completed.

The error message at for the failed requests (sanitized for internal info) looks like this:

````
192.168.32.23 - jeremybmerrill@mycorp.tld [01/Nov/2016:15:19:43 +0000] nginxupstream.internal.mycorp.tld GET nginxupstream.internal.mycorp.local "/js/some_resource.js" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:49.0) Gecko/20100101 Firefox/49.0" 502 0 0.002
2016/11/01 15:19:43 reverseproxy.go:279: http: proxy error: dial tcp: lookup stevedore.adm.svc.prd.local on 192.168.0.69:53: dial udp 192.168.0.69:53: operation was canceled
````

Because requests to either upstream can fail, I assume this is an issue with my deployment of oauth2_proxy. Perhaps it's choking on being asked to make 30ish requests in a single second? I don't know what to make of the `dial udp` `operation was canceled` stuff -- perhaps you do.

If it's useful to know, oauth2_proxy is being run in a Docker container managed by Kubernetes; Go version is 1.7.3. (This accounts for some of the funny looking routing, with that .local address.)

Looking forward to hearing back from you if you can help. Great tool, super useful; I'm very appreciative of it. Please let me know if there's additional information I can offer that's helpful in debugging. Thanks!

**Comment by jehiah** [comment]
@jeremybmerrill interesting. the `operation was canceled` part is odd, but it does implicate DNS resolution from inside your container in general. 

Some ideas that might help troubleshoot: run with `export GODEBUG=netdns=cgo`, write a small Go script to repeatedly call `net.LookupHost(...)` from inside your container w/ some concurrency (matching browser concurrency). If you are having actual DNS server capacity issues you might need to use a local caching dns proxy (I have had good success running [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/doc.html) on every host)

**Comment by jeremybmerrill** [comment]
Ah, that's a very good idea, @jehiah. I'll bug our Kubernetes people and see if occasionally-failing DNS resolution is a plausible thing. And I'll try what you suggest too. Thanks!

**Comment by jeremybmerrill** [comment]
Turns out this is a known bug with our Kubernetes (that I just hadn't encountered before), not a oauth2_proxy problem. Sorry for the false alarm and thanks for the terrific tool.

**Comment by jehiah** [comment]
no worries. thanks for the follow up!

**Comment by caleblloyd** [comment]
@jeremybmerrill can you post a link to the upstream kubernetes issue?  I have hit this on Kubernetes also, but not using `ouath2_proxy`

**Comment by jeremybmerrill** [comment]
@caleblloyd: I'm afraid I don't remember. I'm a mere user of the kubernetes cluster and one of our admins fixed it, I think.

**Comment by sergiosarmentosilva** [comment]
@jeremybmerrill Could you provide some more information about what he did to fix it? I'm having the same issue.

**Comment by jeremybmerrill** [comment]
@sergiosarmentosilva I asked and he didn't remember either. Around that time, we were dealing with some issue where connections were being reused in the kubernetes-dns-proxy, so that when a service moved from one pod to another, the proxy might send traffic for that service to the old pod, resulting in traffic for app A showing up at app B. Another issue we apparently had was sporadic failures in flanneld, which we fixed by restarting flanneld. But I don't think either of these issues was the source of the oauth2_proxy problem... whatever the solution was is lost in the sea of memories. Sorry about that.
