### ISSUE TITLE
Trying to host a static landing page with no luck

### ISSUE THREAD

**Issue by michaeldauria** [bitly/oauth2_proxy#330]
Not sure what I am doing wrong here, but my idea is to have the user land on a page with simple HTML that has links to other reverse proxies. This means that I am trying to serve a static page on `/` like so:

```
upstreams = [
  "file:///srv/app/public/#/",
  "http://internal.remote-service.com/remote-service"
]
```

I see an appropriate mapping log:
```
mapping path "/" => file system "/srv/app/public/"
```

Here is the 404 line:
```
172.17.0.1 - user@gmail.com [21/Nov/2016:08:57:44 +0000] localhost:4180 GET / "/" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36" 404 19 0.000
```

No matter what I try for the fragment section I always see a 404. I have confirmed that the source dir for the static files (`/srv/app/public`) exists and `index.html` is found within. Any advice would be fantastic :)

**Comment by michaeldauria** [comment]
I had fat fingered my configuration :/

It works as documented, assuming that you actually put files in the right places

**Comment by jehiah** [comment]
@michaeldauria thanks for following up here =)
