### ISSUE TITLE
Consider adding dex as a provider

### ISSUE THREAD

**Issue by SEJeff** [bitly/oauth2_proxy#332]
CoreOS have written the most excellent [dex](https://github.com/coreos/dex) web service for allowing oauth2 tokens to come from things like a corporate Active Directory or IPA LDAP server. Consider supporting dex as a provider.

**Comment by janwillies** [comment]
there hasn't been an update on #165 for a year, and dex v2 came out recently. Would be great to have it as a provider for oauth2_proxy

**Comment by ericchiang** [comment]
Updated PR here: #389

**Comment by sokoow** [comment]
+1 Bump, where are you with this? It'd be great to have dex as a provider.
