### ISSUE TITLE
Not redirecting after login.

### ISSUE THREAD

**Issue by pms1969** [bitly/oauth2_proxy#341]
Hi. 

It might just be my poor understanding of how things operate between nginx and oauth2_proxy, but for the life of me, I can't get my setup to redirect to the initial page after login.  I'm using nginx as an ssl terminating proxy for a .net service, and oauth2_proxy is governing access to our swagger pages.

It's running on a windowsservercore docker container.

My nginx.conf looks like so:
```
worker_processes  1;

error_log  logs/error.log  info;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" '
                     '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  logs/access.log  main;

    sendfile        on;

    keepalive_timeout  65;

    upstream oauth2_proxy {
        server 127.0.0.1:4180;
    }

    upstream core_api {
        server 127.0.0.1:8282;
    }

    server {
        listen 8443;
        server_name ...;

        proxy_intercept_errors off;
        proxy_send_timeout 120;
        proxy_read_timeout 300;
        
        client_max_body_size 3G;

        ssl_certificate           c:/app/certs/cert.crt;
        ssl_certificate_key       c:/app/certs/cert.key;

        ssl on;
        ssl_session_cache  builtin:1000  shared:SSL:10m;
        ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
        ssl_prefer_server_ciphers on;

        access_log            logs/access.log;

        keepalive_timeout  5 5;
        proxy_buffering    off;

        add_header Strict-Transport-Security max-age=2592000;

        location = /health {
            return 200 "Healthy!";
        }

        location = /oauth2/auth {
            internal;
            proxy_pass http://oauth2_proxy;
        }

        location /oauth2/ {
            proxy_set_header        Host               $host:$server_port;
            proxy_set_header        X-Real-IP          $remote_addr;
            proxy_set_header        X-Scheme           $scheme;
            proxy_set_header        X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto  $scheme;
            proxy_set_header        X-Forwarded-Port   $server_port;

            proxy_pass              http://oauth2_proxy;
        }
        
        location /swagger {
            auth_request /oauth2/auth;
            error_page 401 = https://$host:$server_port/oauth2/sign_in;
        
            proxy_set_header        Host               $host:$server_port;
            proxy_set_header        X-Real-IP          $remote_addr;
            proxy_set_header        X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto  $scheme;
            proxy_set_header        X-Forwarded-Port   $server_port;
            
            proxy_pass              http://core_api/swagger;
            proxy_read_timeout      90;
        }

        location / {
            proxy_set_header        Host               $host:$server_port;
            proxy_set_header        X-Real-IP          $remote_addr;
            proxy_set_header        X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto  $scheme;
            proxy_set_header        X-Forwarded-Port   8443;

            proxy_pass              http://core_api/;
            proxy_read_timeout      90;
        }
    }
}
```

I start up oauth2_proxy like so:
`oauth2_proxy.exe --email-domain=company.com --provider=azure --azure-tenant=my-tenant-id --upstream=https://0.0.0.0:8443/swagger --http-address=0.0.0.0:4180`
with the appropriate client_id etc environment vars set.

Once I'm authorised, accessing the swagger end points works fine.  It's just the direct return from authorisation takes me to the site root instead of the url I first tried to hit -> for example being unauthorised if I hit https://my.host:8443/swagger I'm immediately sent thru to the login screen.  I then authorise, and am redirected to https://my.host:8443 . I would expect to be redirected to https://my.host:8443/swagger which would then in turn redirect me to https://my.host:8443/swagger/ui/index (due to swagger redirect)

Any help would be very much appreciated.
Cheers,
Paul

**Comment by pms1969** [comment]
I've noticed I have exactly the same behaviour with linux containers.  Works fine after sign in, but the redirect to the requested url is ignored if authentication is required.

I've tied setting the `error_page` uri like so
```
error_page 401 = https://$host:$server_port/oauth2/sign_in?rd=$request_uri;
```
but still no luck.  This just ends up bringing me back to `/oauth2/sing_in?rd=blah.html` so no redirection going on at all.

quite perplexing.

**Comment by pms1969** [comment]
OK,  managed to figure out a workaround.  So anyone else who finds themselves in this situation, here it is:

```
error_page 401 = /oauth2/start?rd=$request_uri;
```

this skips the "sign in with provider" sign in page, but I don't exactly need that anyway.

Closing the ticket.

**Comment by maghoff** [comment]
Thanks for the ideas :) I had the same problem and found a slightly different way out which lets me keep the "sign in with provider"-page. For the `error_page` directive, I redirect to `sign_in` and append an `rd` query argument:

    error_page 401 =307 https://$host:$server_port/oauth2/sign_in?rd=$request_uri;

Then, in the `location` section for `oauth2_proxy`, I pick up that query arg and put it into a header:

    proxy_set_header X-Auth-Request-Redirect $arg_rd;
