### ISSUE TITLE
Project health and attention for issues/patches

### ISSUE THREAD

**Issue by ahmetb** [bitly/oauth2_proxy#348]
This is a nice project with adoption and a community around it, however I am seeing that many pull requests and issues do not get the attention they deserve.

There are quite a few forks with good improvements [like this one](https://github.com/avatao/oauth2_proxy) or [this one](https://github.com/coreos/oauth2_proxy). Not to mention there are TENS of [others forks](https://github.com/bitly/oauth2_proxy/network) that made changes only in the past 30 days.

However this repo did not merge any PRs past 4 months. Seeing that probably discourages a lot of forks to make their patches upstream, which in turn, hurts the broader community and makes it harder to find which one is the blessed fork. I think there's a bit opportunity being missed here. Open source communities are very hard to build and they occur naturally as it happens here, but they're easy to destroy as well.

Especially when it comes to security software, which people deploy to production and trust with their business infrastructure, finding the right and actively patched/maintained fork becomes even more important. As a user, I failed to find the right solution.

I strongly encourage Bitly folks to either spend some time with the patches and issues and give this project the love it deserves, or pick active community members and give them commit access to maintain the project further. Please do not let the community down.

**Comment by redshirtrob** [comment]
I would really like to see a response too. I've very happy with the project and would like to contribute back, but the lack of movement in the past few months makes me wonder if my efforts will be worthwhile. I'd rather not maintain a fork.

**Comment by jan-schulz-k24** [comment]
According to the commit graph, there are at least two forks which seem to have active development: 

https://github.com/brunnels/oauth2_proxy -> commits by @brunnels
https://github.com/avatao/oauth2_proxy -> commits by @gdemarcsek and @oszi (seems to be an org which backs this)

**Comment by jehiah** [comment]
Sorry for the delay in replying; As i'm sure you can appreciate this isn't my top priority day to day. 

I'll take this issue to ❤️ .

I'll try to write up some contributing guidelines to make it easier for me to respond to PRs and accept contributions, and i'll try to recruit some additional folks from the Bitly team to help manage releases here. 

Given the other priorities i have, this project tends to get a burst of activity every few months when i have some time. That said i'm working through getting updated releases on a few projects including this, so now's an ideal time to help shepherd any PR's you feel passionately about, and make sure features from forks are represented well.

**Comment by ahmetb** [comment]
@jehiah I would strongly suggest looking at the community members with active forks and giving them contributor access. This would make it easier for you to keep the project alive outside the company.
