### ISSUE TITLE
Allow exclusion of Domain= in cookies

### ISSUE THREAD

**Issue by leonelwilliams** [bitly/oauth2_proxy#352]
I've set the cookie-name to `__Host-oauth2` in an attempt to get [Cookie Prefixes](https://tools.ietf.org/html/draft-west-cookie-prefixes-05#section-1) ([__Host-](https://tools.ietf.org/html/draft-west-cookie-prefixes-05#section-3.2)) to work but I'm having some issues getting Chrome to accept the cookie.

Section 3.2 forbids setting Domain= but I can't seem to find a vanilla way to exclude Domain= from the cookie oauth2_proxy sends -- could a "none" option be added for -cookie-domain?

**Comment by jehiah** [comment]
@leonelwilliams are you interested in contributing a PR to update the cookie handling to automatically skip setting the domain in these cases?

**Comment by leonelwilliams** [comment]
I don't know anything about golang (I'm mostly on the administrative/spec end of the computery things) so if I were able to somehow conjure up something that works it'd unfortunately be of poor quality and not fit for inclusion ☹️
