### ISSUE TITLE
Windows pre-build binary is not an .exe

### ISSUE THREAD

**Issue by Esfera5** [bitly/oauth2_proxy#353]
https://github.com/bitly/oauth2_proxy/releases/tag/v2.1 points to a tar.gz file which does not contain a .exe file.

**Comment by jehiah** [comment]
@Esfera5 would you be willing to open a PR that fixes the windows build settings in `dist.sh`?

**Comment by Esfera5** [comment]
Sure. Proper solution should consider https://golang.org/doc/code.html. Are you guys willing to move stuff around? I'd rename `main.go` to `oauth2_proxy.go` in which case build cmd would be `go build src/oauth2_proxy.go`. Go toolchain takes care of naming `oauth2_proxy` or `oauth2_proxy.exe`. How does that sound?

**Comment by jehiah** [comment]
`go build` might uses the directory name by default but [`dist.sh`](https://github.com/bitly/oauth2_proxy/blob/master/dist.sh#L25) builds to a different target directory so that it can build up the `tar.gz` release files.

That logic just needs a conditional for handling the `os=windows` case.
