### ISSUE TITLE
403 code for auth_request /oauth2/auth - nginx

### ISSUE THREAD

**Issue by skloss** [bitly/oauth2_proxy#373]
Hey guys,

thanks for looking in to this, i try to get the oauth proxy running under the location ~ /swagger. The way should be ,that you go to the location ~ /swagger,than you get redirected to the proxy, authenticate and get back to the  swagger page. My problem is ,that i cant reach the proxy, i go to the location ~ /swagger it's try to redirect but then i get always a the code "403" or "Access forbidden". I be really stuck here, so any help would be appreciated.

 **Github OAuth:**
Homepage Url: https://xxxx/swagger-ui.html
Callback Url:     https://xxxx/swagger-ui.html

**oauth2_proxy version:** v2.1

**oauth2_proxy config:** 
`--github-org=xxx --github-team=xxx --upstream=http://127.0.0.1:1880 --cookie-secret=xxx --client-id=xxx --client-secret=xxx --email-domain=* --provider=github -pass-basic-auth=true -http-address http://0.0.0.0:4180 --cookie-secure=false`

**oauth2_proxy log:**
```
2017/04/10 16:54:18 oauthproxy.go:455: 127.0.0.1:48957 Cookie "_oauth2_proxy" not present

127.0.0.1 - - [10/Apr/2017:16:54:18 +0200] 127.0.0.1:4180 GET - "/oauth2/auth" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" 403 2255 0.001
```
**nginx access log:**
`xxx.xxx.xxx.xxx - - [10/Apr/2017:16:54:18 +0200] "GET /swagger-ui.html HTTP/1.1" 403 199 "https://xxxxxxxxxxxxxx/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"`

**Nginx config**
```
#server {

#    listen 80 default_server;
#    return 301 https://$host$request_uri;
#}

server {
    listen 80 default_server;
    listen 443 ssl;

    access_log /var/log/nginx/xxx.access.log;
    error_log /var/log/nginx/xxx.error.log error;

    ssl_certificate /etc/nginx/ssl/aws-xxx.crt;
    ssl_certificate_key /etc/nginx/ssl/aws-xxx.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_session_cache  builtin:xxx  shared:SSL:xxx;

    set_real_ip_from x.x.x.x;
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;

    location ~ /swagger(.*)$ {

        auth_request /oauth2/auth;
        error_page 401 = /oauth2/sign_in;

        auth_request_set $user   $upstream_http_x_auth_request_user;
        auth_request_set $email  $upstream_http_x_auth_request_email;
        proxy_set_header X-User  $user;
        proxy_set_header X-Email $email;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_connect_timeout 1;
        proxy_send_timeout 30;
        proxy_read_timeout 30;
        proxy_pass http://127.0.0.1:1880;

    }

    location = /oauth2/auth {
        internal;
        proxy_pass http://127.0.0.1:4180;
    }

    location /oauth2/ {
         proxy_pass       http://127.0.0.1:4180;
         proxy_set_header Host                    $host;
         proxy_set_header X-Real-IP               $remote_addr;
         proxy_set_header X-Scheme                $scheme;
         proxy_set_header X-Auth-Request-Redirect $request_uri;
    }


    location ~ / {
        proxy_pass http://127.0.0.1:1880;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header  X-Forwarded-Proto https;
        proxy_set_header  X-Forwarded-For $remote_addr;
    }
}
```

**Comment by ploxiln** [comment]
oauth2_proxy returned a 403. but nginx is only configured to do an "internal redirect" to the "error_page" `/oauth2/sign_in` for 401 responses.

oauth2_proxy is supposed to return 401 from the `/oauth2/auth` handler, but apparently it is not for you. You may need to compile latest master from source instead of using the binary release.

**Comment by skloss** [comment]
Thx you very much @ploxiln, you solved my problem. 

**Solution:** Compile latest master from source instead of using the binary release v2.1.

**Comment by aptro** [comment]
@ploxiln I am using v2.2 binary release and getting the same error. Do I need to build from master branch
