### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by kminehart** [bitly/oauth2_proxy#379]
Hey are you guys still keeping up with releases?  I'm wanting to make a consistently updated Dockerfile (and helm chart) repository for oauth2_proxy, but I'm realizing that all of the other ones appear to be old because the last release was almost a year ago.

Are the maintainers planning on tagging any releases after 2.1?

Thanks!

**Comment by tanuck** [comment]
+1 for this... would really like to see some more frequent releases. There's also a lot of PR's open that need looking at.

**Comment by tanuck** [comment]
Thanks @jehiah 👍

**Comment by jehiah** [comment]
@tanuck no problem; it's been a long time coming =)
