### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by kevinburke** [bitly/oauth2_proxy#396]
I'm trying to check out version 2.0.1 locally but it's difficult because there's no Git tag corresponding to that release. It would be nice if the release process also included adding Git tags.

**Comment by jehiah** [comment]
Please see https://github.com/bitly/oauth2_proxy/tags

**Comment by kevinburke** [comment]
Yikes, I'm an idiot, sorry.

**Comment by jehiah** [comment]
no worries =)
