### ISSUE TITLE
Htpasswd using an insecure hashing algorithm

### ISSUE THREAD

**Issue by OlofHaglund** [bitly/oauth2_proxy#404]
In your example configuration file it says that you have to use the SHA encryption. Using SHA is not recommend due to not being designed for storing password. Instead it is recommended to use one of the algorithms designed for passwords. Htpasswd has support for the more secure bcrypt. 

> \#\# Additionally authenticate against a htpasswd file. Entries must be created with "htpasswd -s" for SHA encryption 

From htpasswd usage:

> -B  Force bcrypt encryption of the password (very secure).
> -s  Force SHA encryption of the password (insecure).

**Comment by jehiah** [comment]
@OlofHaglund `oauth2_proxy` doesn't use `htpasswd` exactly, it just uses that format. If you would like to contribute and expand the htpasswd format support that would be appreciated.

**Comment by reedloden** [comment]
Looks like https://github.com/openshift/origin/blob/master/pkg/auth/authenticator/password/htpasswd/htpasswd.go supports most formats.
