### ISSUE TITLE
Preference between additional maintainers or a friendly fork?

### ISSUE THREAD

**Issue by statik** [bitly/oauth2_proxy#428]
Hi!

Thank you to everyone who has worked on oauth2_proxy. It has been a valuable tool in many different situations, as can be seen by the 555 forks,  2,594 stars, and 54 open pull requests.

Bitly and the authors have kindly provided this open source software for free, and I am under no delusions that there is an obligation of support.

However, there are many valuable enhancements to this software that have sat unmerged, some for a year or more, from community members attempting to contribute. As I make use of oauth2_proxy in my work, and have paid for or personally written some of the pull requests that are unmerged, I want to do something to change the state of affairs. I regularly build and deploy custom versions of oauth2_proxy for customers, and want those versions to be available as standard releases to the entire community.

I see two ways to provide this:
* The current maintainers open the door to additional maintainers to do work of testing and merging the outstanding PRs, and making new releases.
* I do a friendly fork of oauth2_proxy and start doing separate releases from my fork and advertising them to the community. This friendly fork could be observed for a while, and then bitly maintainers could choose to occasionally merge back.

Any preference from the bitly maintainers or community before I carry on with publishing releases from my own (not yet published) fork of the project?

**Comment by Fodoj** [comment]
My opinion - add more maintainers and, optionally, transfer ownership to new github team

**Comment by reedloden** [comment]
cc @jehiah and @ploxiln

**Comment by tanner-bruce** [comment]
@statik The CoreOS people may be willing to help as well, since they are (somewhat) maintaining their own fork.

**Comment by tpherndon** [comment]
Hi folks,

My name is Peter Herndon, I'm a backend developer at Bitly, and I've been added as a maintainer for the project. I hope to clear up some of the backlog of pull requests, but it'll take some time for me to ramp up on the project. Please bear with me for a bit, and if you have any specific suggestions or concerns, do let us know.

Regarding forks, if the community of users and developers want to anoint a different fork as the primary focus of development, I think it'd be foolish to do anything other than offer support and contributions as we can. Until then, we have no intentions of turning off the lights, and hopefully I'll be able to help keep the backlog to a minimum.

**Comment by statik** [comment]
@tpherndon thats great! I would much prefer to collaborate with you rather than to shift focus elsewhere. 

It seems like we have some intermittent failures happening in travis in the test suite related to a file being checked after it was deleted that are causing a lot of PRs to be marked as failed when really they are fine. I'm not very clear on how to debug/fix this flaky test. https://travis-ci.org/bitly/oauth2_proxy/jobs/238279884#L430

Another question: in .travis.yml do we definitely need builds to be done with both go 1.7.5 and 1.8.1? It seems like overkill since only one version is released, but I don't know if there is a reason to check for 1.7.5 compatibility during the build.

My suggestion for how to tackle the pile of pending PRs would be to start with the new providers, as it seems like those are least likely to break things for existing users, then move on to the other stuff.

If there is anything that you would like help with, please feel free to tag me, I'm happy to help with code reviews, testing, or even fixing up PRs so they are mergeable.

**Comment by reedloden** [comment]
@tpherndon, just wanted to follow-up, as it's been almost two weeks. Haven't seen any actions taken to revive this project, so just wanting to know what your timeline is. Again, there are several people who would be happy to help takeover and/or fork this project if that's a better fit.

**Comment by reedloden** [comment]
@statik -- thoughts on reopening this? Seems like it's time to move forward with an alternative path based on inaction.

**Comment by SEJeff** [comment]
@reedloden It looks like they are indeed working on it. I see 6 merged PRs within the past 2 weeks (thanks @jehiah!)

https://github.com/bitly/oauth2_proxy/commits/master

Would bitly be open to adding non-bitly employees who have contributed extensively to this codebase as maintainers to do some of the triaging and simple pull requests? Some PRs, such as #444, are a no brainer to just merge.
