### ISSUE TITLE
Missing setting for email validation

### ISSUE THREAD

**Issue by svanschalkwyk** [bitly/oauth2_proxy#432]
```2017/08/05 23:13:31 main.go:103: Invalid configuration:
  missing setting for email validation: email-domain or authenticated-emails-file required.
      use email-domain=* to authorize all email addresses
```
I've tried all variations of email-domain, email-domains,"*","mydomain.com" , ["*"], ".mydomain.com" etc.
Keep on getting the error message above.

System:
Ubuntu 17.04, 4.10.0-30-generic
oauth2_proxy-2.2.0.linux-amd64.go1.8.1

**Comment by svanschalkwyk** [comment]
I have also placed a file "emails", with one email per line in the same directory as the .cfg file.
My cfg entry is ```authenticated_emails_file = "./emails"```
The result in the error log is this: 
```2017/08/05 23:26:14 validator.go:23: using authenticated emails file ./emails
2017/08/05 23:26:14 watcher.go:65: failed to add emails to watcher: no such file or directory```

**Comment by svanschalkwyk** [comment]
I have the following: ```authenticated_emails_file = "/var/oauth2_proxy/emails" ```
Containing one email s@gmail.com.
When I sign on with another gmail email, it still allows me to pass.
What am I doing wrong?

**Comment by jan-schulz-k24** [comment]
We use this commandline:  `/path/to/bin/oauth2_proxy -email-domain=company.de -authenticated-emails-file=/path/to/additional-authorized-emails [...]` to let every account from the company autenticate (via ` -email-domain=company.de`) and some additional test accounts (like xyz@gmail.com, via entries in that file `-authenticated-emails-file=/path/to/additional-authorized-emails`).

**Comment by svanschalkwyk** [comment]
Thank you. I have even gone so far as to omit the email-domain entirely. It is still allowing accounts that are not in the emails file. Will try again tomorrow.

**Comment by svanschalkwyk** [comment]
If I comment out the emails file, and enter a value (in the conf file) for ```email-domain="remcam.net"``` or ```email-domains=["remcam.net"]``` (as per https://raw.githubusercontent.com/bitly/oauth2_proxy/master/contrib/oauth2_proxy.cfg.example) , it gives me this:
```main.go:103: Invalid configuration:  missing setting for email validation: email-domain or authenticated-emails-file required.  use email-domain=* to authorize all email addresses ```
I have also tried variations on ```".remcam.net", "*.remcam.net"``` (as per some examples on the net) etc.

**Comment by svanschalkwyk** [comment]
The problem stems from here in Options.go, line 136:
```	if o.AuthenticatedEmailsFile == "" && len(o.EmailDomains) == 0 && o.HtpasswdFile == "" {
		msgs = append(msgs, "missing setting for email validation: email-domain or authenticated-emails-file required.\n      use email-domain=* to authorize all email addresses") }```
Somehow o.EmailDomans (String[]) isn't populated.

**Comment by svanschalkwyk** [comment]
jan-schulz-k24 : I am using these cmd line settings:
```-provider=google
    -email-domain=remcam.net
    -cookie-secure=true
    -cookie-domain=remcam.net
    -cookie-expire=24h    
    -authenticated-emails-file="emails"
```
Still validating every user. I have a cookie remover which removes all cookies for the site, so that can't be the problem. Anybody have any idea?
PS. The email-domain setting isn't read correctly fron the config file. Only cli is not throwing an exception.

**Comment by ploxiln** [comment]
Your issue with email-domain vs email-domains is that for the command-line argument it is singular, repeated, and using dashes: `-email-domain=first.com -email-domain=second.com`, while for the config file it is plural, array, and using underscores: `email_domains = ["first.com", "second.com"]`, see https://github.com/bitly/oauth2_proxy/blob/v2.2/options.go#L32 (also note that in the config `authenticated_emails_file` uses underscores).

Once you've specified the options correctly, you'll want to *not* specify email-domain, because any email in that domain will be accepted regardless of authenticated-emails-file. It's a "union" rather than an "intersection" between those rules - see https://github.com/bitly/oauth2_proxy/blob/v2.2/validator.go#L80

**Comment by svanschalkwyk** [comment]
Thanks, I have the settings where it won't just fail with the email-domains error. I now have a problem that all users are validated, even those not in the domain (s@gmail.com) or outside the authenticated emails file (s@remcam.net). Please see https://github.com/bitly/oauth2_proxy/issues/434 . If you have an idea why that is, I'd appreciate it very much!
