### ISSUE TITLE
Content-Length forwarded with auth request leading to hanging

### ISSUE THREAD

**Issue by fastest963** [bitly/oauth2_proxy#442]
When a POST request is made with a body, a request is made to oauth2_proxy:
```
GET /oauth2/auth HTTP/1.1
Host: [redacted]
X-Forwarded-Proto: https
X-Scheme: https
X-Auth-Request-Redirect: /api/auth/login
Content-Length: 77
Accept-Encoding: gzip
accept: application/json, text/plain, */*
cache-control: no-cache
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3192.0 Safari/537.36
content-type: application/json;charset=UTF-8
accept-language: en-US,en;q=0.8
cookie: [redacted]
```

The GET request has a `Content-Length` header which causes oauth2_proxy to hang waiting for a body. In order to fix this we've added:
```
proxy_pass_request_body off;
proxy_set_header Content-Length "";
```
to the `location /oauth2/` block.

Does that make sense? If so, it should be added to the README to prevent others from having this same problem.

**Comment by ploxiln** [comment]
Hmm, that's interesting - the nginx documentation suggests the same thing: http://nginx.org/en/docs/http/ngx_http_auth_request_module.html#example

I only started using "auth_request" mode this year, and I did find that I had to go back to the original "proxy" mode for a web app called nsqadmin, in order for some actions to work. This would explain it.

One small problem is that this simple fix would break signing in with a username and password directly (enabled with `--htpasswd-file`). So maybe we'd need a separate block for `/oauth2/auth`.
