### ISSUE TITLE
Wrong version in Godeps file for cloud.google.com/go/compute/metadata

### ISSUE THREAD

**Issue by philippthun** [bitly/oauth2_proxy#458]
Due to an [issue in gpm](https://github.com/pote/gpm/issues/91), some packages are not checked out correctly. When manually checking out `cloud.google.com/go/compute/metadata` to version `v0.7.0` (as specified in the Godeps file), the following error is reported when running `go test`:

```
vendor/cloud.google.com/go/internal/retry.go:21:2: cannot find package "github.com/googleapis/gax-go" in any of:
	/Users/me/git/oauth2_proxy-boshrelease/src/github.com/bitly/oauth2_proxy/vendor/github.com/googleapis/gax-go (vendor tree)
	/usr/local/go/src/github.com/googleapis/gax-go (from $GOROOT)
	/Users/me/git/oauth2_proxy-boshrelease/src/github.com/googleapis/gax-go (from $GOPATH
```

**Comment by talam** [comment]
resolved in https://github.com/bitly/oauth2_proxy/pull/459.
