### ISSUE TITLE
Cookie not present

### ISSUE THREAD

**Issue by rsps-jesper** [bitly/oauth2_proxy#476]
The problem, I think, is ("10.0.0.1") Cookie "_oauth2_proxy" not present. Should the firewall be reconfigured ? Or why is below not working :

I have been trying the different suggestions in #259 and #238 but I cant get the cookie to the server. 

picture of what I'm trying to achieve:
![image](https://user-images.githubusercontent.com/15262263/31544639-12a8b7d2-b01c-11e7-971e-0cc17a3e0f36.png)

Log of sign-in attempt:

$ sudo oauth2_proxy -config=/etc/oauth2_proxy.cfg 

oauthproxy.go:130: mapping path "/" => upstream "http://localhost:1234"
oauthproxy.go:157: OAuthProxy configured for Google Client ID: ...
oauthproxy.go:167: Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domain:company.com refresh:after 1h0m0s
http.go:81: HTTPS: listening on [::]:54321
oauthproxy.go:602: 10.0.0.1:40364 ("10.0.0.1") Cookie "_oauth2_proxy" not present
 GET - "/oauth2/auth" HTTP/1.0
 GET - "/oauth2/sign_in" HTTP/1.0
 oauthproxy.go:602: 10.0.0.1:21524 ("10.0.0.1") Cookie "_oauth2_proxy" not present
 GET - "/oauth2/auth" HTTP/1.0 
 GET - "/oauth2/sign_in" HTTP/1.0 
 GET - "/oauth2/start?rd=%2F" HTTP/1.0 
oauthproxy.go:527: 10.0.0.1:35781 error redeeming code got 401 from "https://www.googleapis.com/oauth2/v3/token" {
 "error": "invalid_client",
 "error_description": "Unauthorized"
}
oauthproxy.go:349: ErrorPage 500 Internal Error Internal Error
10.0.0.1 - www.company.com:54321 GET - "/oauth2/callback?state=..." 
oauthproxy.go:602: 10.0.0.1:35781 Cookie "_oauth2_proxy" not present
10.0.0.1 - www.company.com:54321 GET - "/favicon.ico" HTTP/1.1 

client / chrome dev tools show a cookie named : _oauth2_proxy_csrf 

**oauth2_proxy_config:**

https_address = ":54321"
tls_cert...
tls_key...
upstreams = ["http://localhost:1234"]

 pass_basic_auth = true
 pass_user_headers = true
 pass_host_header = false
 
 client_id ...
 client_secret ...
 
 cookie_name = "_oauth2_proxy"
 cookie_secret = "..."	
 cookie_domain = "company.com"
 cookie_expire = "168h"
 cookie_refresh = "1h"
 cookie_secure = true
 cookie_httponly = true
 
 
 **company.com nginx block**
 server{
 ssl stuff...
 
 add_header Strict-Transport-Security max-age=2592000;
 	location / {
		auth_request /oauth2/auth;
		error_page 401 = /oauth2/sign_in;

	    auth_request_set $user   $upstream_http_x_auth_request_user;
	    auth_request_set $email  $upstream_http_x_auth_request_email;
	    proxy_set_header X-User  $user;
	    proxy_set_header X-Email $email;

	    auth_request_set $auth_cookie $upstream_http_set_cookie;
	    add_header Set-Cookie $auth_cookie;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_connect_timeout 1;
        proxy_send_timeout 30;
        proxy_read_timeout 30;

    	proxy_pass http://company.com:54321;

  	}

 	location /oauth2/ {
	proxy_pass       https://company.com:54321;
	proxy_set_header Host                    $host;
    	proxy_set_header X-Real-IP               $remote_addr;
    	proxy_set_header X-Scheme                $scheme;
    	proxy_set_header X-Auth-Request-Redirect $request_uri;
  	}
}

**Comment by jehiah** [comment]
Not the error getting an access token from google at the end of the oauth flow

```
oauthproxy.go:527: 10.0.0.1:35781 error redeeming code got 401 from "https://www.googleapis.com/oauth2/v3/token" {
"error": "invalid_client",
"error_description": "Unauthorized"
}
oauthproxy.go:349: ErrorPage 500 Internal Error Internal Error
10.0.0.1 - www.company.com:54321 GET - "/oauth2/callback?state=..."
```

Once you fix that, you should be fine. I assume this probably indicates that your google oauth app client secret isn't correctly configured.

**Comment by rsps-jesper** [comment]
I had mistakenly copied googles Client ID twice, making the client secret worthless -_- Thanks for the hint in the right direction!

**Comment by jehiah** [comment]
@rsps-jesper happy to help!
