### ISSUE TITLE
Feature Request: Checksum Support for Releases

### ISSUE THREAD

**Issue by BenCoffeed** [bitly/oauth2_proxy#479]
I would like to  be able to checksum verify downloaded releases to guard against MITM attacks. 
Do you currently post the checksums or have a method for verifying?

**Expected Behavior**

Check-sum provided for a release that can be calculated by the client after download and compared to posted checksum to confirm validity of downloaded code.

**Actual Behavior**

no checksum available for a release

**Comment by jehiah** [comment]
👍  @BenCoffeed do you know of a Go based project that does this well?

My current workflow is to run `./dist.sh` locally on my laptop to build releases, but i know that bakes in directory information etc and isn't 100% reproducible.

**Comment by BenCoffeed** [comment]
@jehiah I haven't used any personally, but [Go Releaser](https://github.com/goreleaser/goreleaser) looks neat.

**Comment by talam** [comment]
Completed in https://github.com/bitly/oauth2_proxy/pull/503
