### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by draganavr** [bitly/oauth2_proxy#499]
Hi guys,

trying to set up oauth+nginx google authentication for AWS Kibana on ec2 instance but getting 404 page not found.

Here is the configuration

### nginx - no ssl

server {
  listen 80;
  server_name example.com;

  location / {
    proxy_pass http://127.0.0.1:4180;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header Authorization "";
    proxy_hide_header Authorization;
    proxy_connect_timeout 1;
    proxy_send_timeout 30;
    proxy_read_timeout 30;
  }
}

### oauth
      --upstream=https://aws_kibana_link/_plugin/kibana/
      --client-id=google_client_id
      --client-secret=google_secret
      --email-domain=email_domain
      --cookie-secure=false
      --cookie-secret=some_secret
      --request-logging=true
      --pass-basic-auth=false
      --pass-user-headers=false
      --pass-host-header=false
      --pass-access-token=false

### error output from the console
Nov 09 13:23:18 ip oauthproxy[30179]: 2017/11/09 13:23:18 oauthproxy.go:130: mapping path "/_plugin/kibana/" => upstream "https://the_aws_link.com"
Nov 09 13:23:18 ip oauthproxy[30179]: 2017/11/09 13:23:18 oauthproxy.go:157: OAuthProxy configured for Google Client ID: 
Nov 09 13:23:18 ip oauthproxy[30179]: 2017/11/09 13:23:18 oauthproxy.go:167: Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domain:<default> refresh:disabled
Nov 09 13:23:18 ip oauthproxy[30179]: 2017/11/09 13:23:18 http.go:49: HTTP: listening on 127.0.0.1:4180
Nov 09 13:27:02 ip oauthproxy[30179]: ip - some@mail.com [09/Nov/2017:13:27:02 +0000] instance_domain.com GET - "/" HTTP/1.0 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/62.0.3202.75 Chrome/62.0.3202.75 Safari/537.36" 404 19 0.000

Login seems successful but the redirection is not working. After the login if I add /_plugin/kibana/ to the link it opens Kibana web fine.
Also --upstream= without /_plugin/kibana/ works perfect (which is the elasticsearch link).

Any help appreciated.
Thanks

**Comment by ploxiln** [comment]
Assuming you initially visited http://127.0.0.1:4180/ with your browser, there's no mechanism/feature that redirects from `/` to `/_plugin/kibana`. The reason you can put the path in the upstream is to be able to have multiple upstreams, and choose between them based on path. There's no redirect related to that (if there were multiple, which would it do?)

You could have nginx do that redirect, from *exactly* `/` to `/_plugin/kibana/`

**Comment by draganavr** [comment]
@ploxiln thanks for the clarification. I've already tried the nginx redirect but it breaks the oauth, its getting in loop in the login part. But anyway above info is enough.
