### ISSUE TITLE
Restricting auth to specific google-groups not working

### ISSUE THREAD

**Issue by natalysheinin** [bitly/oauth2_proxy#515]
Following instructions here:
https://github.com/bitly/oauth2_proxy#restrict-auth-to-specific-google-groups-on-your-domain-optional

When using the command line flags, `google-group`, `google-admin-email`, and `google-service-account-json`, how can I test the Admin SDK call with the parameters I plan to supply to those options?

Also, where exactly in the oauth-proxy do I include these options? Are there any examples?

**Comment by ploxiln** [comment]
> where exactly in the oauth-proxy do I include these options?

You can specify them in the command which runs oauth2_proxy, like so:

```
oauth2_proxy --provider=google --google-group=... --google-admin-email=...
```

Or you can specify them in a config file (like https://github.com/bitly/oauth2_proxy/blob/master/contrib/oauth2_proxy.cfg.example) and just specify the config file in the command:

```
oauth2_proxy --config=/opt/dir/oauth2_proxy.cfg
```

In the config file, _almost all_ options use underscores instead of dashes, you can see them all here: https://github.com/bitly/oauth2_proxy/blob/master/options.go#L37-L39

I suggest getting the simplest setup working first - not limiting to a particular group - and then adding on further options/features after you get it working.

**Comment by natalysheinin** [comment]
Thanks for this response. 
I do have the simplest setup working already.

Strange though, following the instructions and using all the correct flag, I am getting this error when I run the command:
`auth2_proxy --provider=google --google-group=... --google-admin-email=...`

```Invalid configuration:
  missing setting: upstream
  missing setting for email validation: email-domain or authenticated-emails-file required.
      use email-domain=* to authorize all email addresses```

Have you ran into this error?

**Comment by ploxiln** [comment]
It expects to be used to authenticate users of a particular G-Suite account who are all given an email address with the company/organization domain, like `yourname@organization.com`, in which case you specify `--email-domain=organization.com`. If email address is really not applicable for your setup, you can specify `--email-domain=*` which means any email domain / address.

**Comment by natalysheinin** [comment]
Great, okay, I added all the correct command line options,  but there is no difference in the oauth proxy behaviour. Basically, the proxy is not restricting access as expected despite all configurations being correct.

**Comment by drichert** [comment]
@natalysheinin Was this resolved? I'm running into the same issue

**Comment by natalysheinin** [comment]
@drichert I can't remember how I resolved this, but are you passing all of necessary flags?

**Comment by civik** [comment]
I just wasted about 40 mins on this.

https://github.com/bitly/oauth2_proxy/blob/master/options.go#L34

cmd-line flag is "email-domain" while the config file item is "email_domain**s**"
