### ISSUE TITLE
Support for multiple slash upstream

### ISSUE THREAD

**Issue by raravena80** [bitly/oauth2_proxy#539]
Somehow this doesn't work for my upstream

`http://myapp:8080/ui/#/group/%2Fmygroup`

apparently it just uses the `ui` path

I suppose the issue is with hashes `#` in the path

**Comment by jehiah** [comment]
@raravena80 values after the `#` are never sent to the server during a page request (on any site, not anything specific to `oauth2_proxy`), so that isn't context `oauth2_proxy` can use to route to the upstream.
