### ISSUE TITLE
adding two email domains

### ISSUE THREAD

**Issue by anilaws** [bitly/oauth2_proxy#576]
i want to allow two email domains using command line, can anyone tell me how to do that?
can i do
./oauth2_proxy \
   --email-domain="company1.com","company2.com"

**Comment by ploxiln** [comment]
you do it by using the flag multiple times:

> ./oauth2_proxy --email-domain=company1.com --email-domain=company2.com

**Comment by anilaws** [comment]
Thanks for the quick response, i appreciate it!
