### ISSUE TITLE
Cannot get authorization against Google Groups working

### ISSUE THREAD

**Issue by borremosch** [bitly/oauth2_proxy#582]
I have tried following the instructions in the readme to the letter, but I cannot get authorization against Google Groups working. When I look at the logs of my proxy pod, I see:

```
2018/05/02 14:43:32 google.go:192: error fetching user: Get https://www.googleapis.com/admin/directory/v1/users/xxx%40xxx.com?alt=json: oauth2: cannot fetch token: 401 Unauthorized
Response: {
  "error" : "unauthorized_client",
  "error_description" : "Client is unauthorized to retrieve access tokens using this method."
}
```

I have re-read the instructions 5 times, but I just cannot seem to figure where I'm going wrong. Everything works fine when I disable group checking. Any suggestions are very welcome.

**Comment by borremosch** [comment]
It turns out there is a ridiculous bug in the G Suite admin panel. When adding acces for an API client under Security -> Advanced, the client name has to be a number. The Service account ID will also be accepted as an input, and it will be rewritten to the client ID number, makign everyhting look fine. but for mysterious reasons it will result in the problem I described above.

**Comment by ptous** [comment]
Thank you for posting about this behavior in the admin panel. I was pulling my hair out and this very thing was the cause.
