### ISSUE TITLE
Live console comes up on executable start - any way to background it?

### ISSUE THREAD

**Issue by blakemartin** [bitly/oauth2_proxy#584]
Hiya!

When I start oauth2_proxy I get a live console with the logging.  If I try to background it, the live console still comes up, but now if I press enter interactively it'll quit and the process will be backgrounded.  I've tried feeding carriage returns to it, to no avail.

I must be missing something here, but I don't see any switches in the docs for forcing the service to background.  

Systemd gets cranky when processes don't background properly.  Thoughts?

Cheers!

**Comment by ploxiln** [comment]
oauth2_proxy does not background itself, it just starts a process to be managed by your favorite service manager, and logs to stdout/stderr which should also be handled by your service manager. systemd in fact prefers such processes! just use `Type=simple`

**Comment by blakemartin** [comment]
@ploxiln - oops, I had `type=forking`.  Totally my bad here.  Thanks!
