### ISSUE TITLE
Support for ignoring specific paths.

### ISSUE THREAD

**Issue by pauldotknopf** [bitly/oauth2_proxy#622]
I need a very specific page unsecured.

Maybe support for a regex to match against paths to ignore?

**Comment by pauldotknopf** [comment]
What configuration is that a part of? It doesn't look like a `oauth2_proxy` config file ([here](https://github.com/bitly/oauth2_proxy/blob/master/contrib/oauth2_proxy.cfg.example)).

**Comment by alberttriasmansilla** [comment]
No, it is the configuration of the nginx that is calling the oauth2_proxy

**Comment by ermik** [comment]
@pauldotknopf oauth2-proxy has `-skip-auth-regex ` config for skipping auth on a specific path:
https://github.com/bitly/oauth2_proxy/blame/2db0443e0484d8b8ab7b23cda752ac30ea5241d8/README.md#L219

**Comment by pauldotknopf** [comment]
Sorry I missed that, brilliant!
