### ISSUE TITLE
oauth2_proxy with DEX on Kubernetes

### ISSUE THREAD

**Issue by Drupi** [bitly/oauth2_proxy#640]
Hello, 

Is there someone who succesfully use ouath2 on K8S with DEX and can share a deployment conf , how to start it with correct issuer-url and provider ?

**Comment by exodussystem** [comment]
Looking for the same thing
@Drupi Did you find any documentation? Mind to share?

**Comment by ccojocar** [comment]
@Drupi @exodussystem check out the https://github.com/jenkins-x/sso-operator. It has a helm chart for dex with cert-manager integration, and also you can provision the oauth2_proxy as a Kuberntes CRD in front of a service.
