### ISSUE TITLE
how to handle the callback url and get the login google emaill account?

### ISSUE THREAD

**Issue by wuweizi55** [bitly/oauth2_proxy#670]
I used google js (gapi) client implement google authentication before, when user completed google login flow, the user information can be retrieved from auth2.currentUser.get().

I try to use oauth2_proxy as Google authentication Proxy, and following is get from callback ur, my question is, how to get the login google emaill account and how to return the value back to my login page?
http://xxxxxxx/oauth2/callback/?state=7ff7f34389c43bcbbabcbcf157fe0cfc:/&code=4/mACu0cuE2zCxGSyaZDhSKuH2svQxbYlnc6UdxL2j2qxq3YH5MAFPdGFtn9djNfu-5Ab03nZuaYNpyEdvnmLgo4c&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email

Thanks.

**Comment by lelvisl** [comment]
Did you solve this problem?
