### ISSUE TITLE
proxying transmission web

### ISSUE THREAD

**Issue by fvitorc** [bitly/oauth2_proxy#94]
Trying to proxy to transmission web will return an error page because of missing X-Transmission-Session-Id header. Normal nginx proxying uses the directive "proxy_pass_header X-Transmission-Session-Id;". Is it possible to do the same thing with google_auth_proxy??

**Comment by jehiah** [comment]
It's not possible to set custom headers directly with oauth2_proxy, but you can use nginx->oauth2_proxy->transmission. If you set the headers in Nginx in that configuration, oauth2_proxy will pass them along.
