### ISSUE TITLE
Why not use the Request.BasicAuth() in the basic auth handler?

### ISSUE THREAD

**Issue by AjayTripathy** [bitly/oauth2_proxy#97]
[CheckBasicAuth()] (https://github.com/bitly/google_auth_proxy/blob/9047920e90f0f571d1870c9b8677b26089740199/oauthproxy.go#L526) seems to re-implement [net/http's Request.BasicAuth() method] (http://golang.org/src/net/http/request.go?s=16575:16641#L518). Any reason for this that I might be missing? The code is straightforward enough, but it seems reasonable to use the base net/http library to do this, as it would reduce the amount of coding and testing necessary here, and instinctively I'd prefer to use base libraries anywhere security is involved. Happy to send a pull request for the refactor if you guys decide it's worth it!

**Comment by jehiah** [comment]
@AjayTripathy good question.

 `Request.BasicAuth()` showed up in Go 1.4 https://github.com/golang/go/commit/29f9f3ec80237ff0b2eb17f042747c08a10e0a14 so we can't rely on it completely (I still want to maintain Go 1.3.3 compatibility). We could update the current function to mirror Go 1.4's implementation of that parsing, and we could also move that logic into a separate file and pivot on build tags to use the stdlib in 1.4+

Care to contribute a patch for either of those things?

**Comment by AjayTripathy** [comment]
Sure, I'm happy to work on a patch.
